import { useCallback, useEffect, useRef, useState } from "react";
import type { Agent, Category } from "../../types";
import { Modal, ModalHeader, ModalBody, ModalFooter, Button, Input, FormField } from "../ui";
import ManualPathPickerDialog from "../project-manager/ManualPathPickerDialog";
import { useProjectManagerPathTools } from "../project-manager/useProjectManagerPathTools";
import CategorySelectStep from "./CategorySelectStep";
import DirectiveEditorStep from "./DirectiveEditorStep";
import GitImportPanel from "../git-import/GitImportPanel";
import { useI18n } from "../../i18n";
import { getFigmaInfo } from "../../api/synapse";
import { fetchDirectiveTemplates, type DirectiveTemplateItem } from "../../api/organization-projects";
import { useUiStore } from "../../store/uiStore";

export type ProjectRoleAssignments = { pm: string | null; pl: string | null; dev: string | null };

interface ProjectCreateModalProps {
  categories: Category[];
  agents: Agent[];
  onConfirm: (params: { name: string; categoryId: string | null; project_path: string; core_goal?: string; agentIds: string[]; roleAssignments: ProjectRoleAssignments; figma_url?: string | null; directive?: string | null; directive_type_slug?: string | null }) => void;
  onGitHubComplete?: (projectId: string) => void;
  onClose: () => void;
}

type Step = "category" | "directive" | "info" | "agent" | "github";

const CLI_PROVIDERS = new Set(["claude", "codex", "gemini", "opencode", "copilot", "antigravity", "cursor", "ollama"]);


const PROVIDER_LABEL: Record<string, string> = {
  claude: "Claude Code",
  codex: "Codex CLI",
  gemini: "Gemini CLI",
  opencode: "OpenCode",
  copilot: "Copilot",
  antigravity: "Antigravity",
  cursor: "Cursor",
  ollama: "Ollama",
};

export default function ProjectCreateModal({ categories, agents, onConfirm, onGitHubComplete, onClose }: ProjectCreateModalProps) {
  const [step, setStep] = useState<Step>("category");
  const [selectedCategoryId, setSelectedCategoryId] = useState<string | null>(null);
  const [projectName, setProjectName] = useState("");
  const [projectPath, setProjectPath] = useState("");
  const [coreGoal, setCoreGoal] = useState("");
  const [roleAssignments, setRoleAssignments] = useState<ProjectRoleAssignments>({ pm: null, pl: null, dev: null });
  const [selectedRoleSlot, setSelectedRoleSlot] = useState<"pm" | "pl" | "dev" | null>(null);
  const [figmaUrl, setFigmaUrl] = useState("");
  const [figmaConnected, setFigmaConnected] = useState<boolean | null>(null);
  const [submitted, setSubmitted] = useState(false);
  const [busy, setBusy] = useState(false);
  const [pathAutoGenerated, setPathAutoGenerated] = useState(false);
  const [directive, setDirective] = useState("");
  const [directiveTypeSlug, setDirectiveTypeSlug] = useState<string | null>(null);
  const [directiveTemplates, setDirectiveTemplates] = useState<DirectiveTemplateItem[]>([]);
  const autoAdvanceTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

  // Load directive templates on mount
  useEffect(() => {
    fetchDirectiveTemplates().then(setDirectiveTemplates).catch(() => {});
  }, []);

  const { t, language } = useI18n();
  const { openWindow } = useUiStore();

  const pathTools = useProjectManagerPathTools({
    t,
    projectPath,
    pathToolsVisible: step === "info",
  });

  const cliAgents = agents.filter((a) => CLI_PROVIDERS.has(a.cli_provider));

  const handlePathChange = (value: string) => {
    setProjectPath(value);
  };

  const handleCategorySelect = (id: string) => {
    setSelectedCategoryId(id);
    const cat = categories.find((c) => c.id === id);
    if (cat?.slug === "design") {
      setFigmaConnected(null);
      getFigmaInfo().then((info) => setFigmaConnected(info.connected)).catch(() => setFigmaConnected(false));
    }
    // Load directive template for this category
    const tpl = directiveTemplates.find((t) => cat?.slug === t.slug);
    if (tpl) {
      setDirective(tpl.template);
      setDirectiveTypeSlug(tpl.slug);
    }
    if (autoAdvanceTimer.current) clearTimeout(autoAdvanceTimer.current);
    autoAdvanceTimer.current = setTimeout(() => setStep("directive"), 300);
  };

  const handleOpenBrowser = useCallback(async () => {
    pathTools.setManualPathPickerOpen(true);
    await pathTools.loadManualPathEntries(undefined);
  }, [pathTools]);

  const handlePathSelected = useCallback(() => {
    if (pathTools.manualPathCurrent) {
      setProjectPath(pathTools.manualPathCurrent);
      setPathAutoGenerated(false);
    }
    pathTools.setManualPathPickerOpen(false);
  }, [pathTools]);


  const selectedCategory = categories.find((c) => c.id === selectedCategoryId) ?? null;
  const canConfirmInfo = projectName.trim().length > 0 && projectPath.trim().length > 0;
  const canConfirmAgent = !!roleAssignments.pm && !!roleAssignments.pl && !!roleAssignments.dev;

  const handleConfirm = () => {
    setSubmitted(true);
    if (!canConfirmInfo || !canConfirmAgent) return;
    setBusy(true);
    const agentIds = Array.from(new Set([roleAssignments.pm, roleAssignments.pl, roleAssignments.dev].filter(Boolean) as string[]));
    onConfirm({
      name: projectName.trim(),
      categoryId: selectedCategoryId,
      project_path: projectPath.trim(),
      core_goal: coreGoal.trim() || (selectedCategory ? `${selectedCategory.name_ko ?? selectedCategory.name} 프로젝트` : undefined),
      agentIds,
      roleAssignments,
      figma_url: figmaUrl.trim() || null,
      directive: directive.trim() || null,
      directive_type_slug: directiveTypeSlug,
    });
  };

  const categoryDisplayName = (cat: Category) => language === "ko" ? cat.name_ko ?? cat.name : cat.name;

  const STEPS: { key: Step; label: string }[] = step === "github"
    ? [{ key: "github", label: "Git Import" }]
    : [
        { key: "category", label: t({ ko: "① 유형", en: "① Type", ja: "① タイプ", zh: "① 类型" }) },
        { key: "directive", label: t({ ko: "② 디렉티브", en: "② Directive", ja: "② ディレクティブ", zh: "② 指令" }) },
        { key: "info", label: t({ ko: "③ 정보", en: "③ Info", ja: "③ 情報", zh: "③ 信息" }) },
        { key: "agent", label: t({ ko: "④ 에이전트", en: "④ Agents", ja: "④ エージェント", zh: "④ 代理" }) },
      ];

  const mono: React.CSSProperties = { fontFamily: "var(--th-font-mono)" };

  return (
    <>
      <Modal open onClose={onClose} width="md">
        <ModalHeader onClose={onClose}>
          {t({ ko: "새 프로젝트", en: "New Project", ja: "新規プロジェクト", zh: "新建项目" })}
        </ModalHeader>

        {/* Step indicator */}
        <div className="flex items-center gap-0 px-5 pt-3 pb-0" style={{ borderBottom: "1px solid var(--th-border)" }}>
          {STEPS.map((s) => (
            <button
              key={s.key}
              type="button"
              onClick={() => {
                if (s.key === "agent" && !canConfirmInfo) return;
                if (s.key === "github") return;
                setStep(s.key);
              }}
              className="px-3 py-2 border-b-2 transition-colors"
              style={{
                ...mono,
                fontSize: "10px",
                fontWeight: step === s.key ? 700 : 400,
                color: step === s.key ? "var(--th-accent)" : "var(--th-text-muted)",
                borderColor: step === s.key ? "var(--th-accent)" : "transparent",
                cursor: "pointer",
              }}
            >
              {s.label}
            </button>
          ))}
          {step === "github" && (
            <button
              type="button"
              onClick={() => setStep("category")}
              className="ml-auto px-2 py-1 text-[10px] font-mono"
              style={{ color: "var(--th-text-muted)" }}
            >
              ← {t({ ko: "일반 생성으로", en: "Normal create", ja: "通常作成へ", zh: "普通创建" })}
            </button>
          )}
        </div>

        <ModalBody>
          {/* ── STEP: GitHub 임포트 ── */}
          {step === "github" && (
            <GitImportPanel
              onComplete={({ projectId }) => {
                onGitHubComplete?.(projectId);
              }}
              onCancel={() => setStep("category")}
            />
          )}

          {/* ── STEP 1: 유형 선택 ── */}
          {step === "category" && (
            <>
              <p className="text-xs mb-3" style={{ color: "var(--th-text-muted)" }}>
                {t({ ko: "어떤 종류의 프로젝트인가요?", en: "What kind of project is this?", ja: "どの種類のプロジェクトですか？", zh: "这是什么类型的项目？" })}
              </p>
              <CategorySelectStep
                categories={categories}
                selectedId={selectedCategoryId}
                onSelect={handleCategorySelect}
              />
              {/* GitHub 임포트 진입 */}
              <div className="mt-4 pt-4" style={{ borderTop: "1px solid var(--th-border)" }}>
                <button
                  type="button"
                  onClick={() => setStep("github")}
                  className="w-full flex items-center gap-3 px-4 py-3 transition-colors"
                  style={{
                    ...mono,
                    fontSize: "12px",
                    border: "1px solid var(--th-border)",
                    background: "var(--th-hover-overlay-subtle)",
                    color: "var(--th-text-secondary)",
                    cursor: "pointer",
                    borderRadius: 0,
                  }}
                  onMouseEnter={(e) => { (e.currentTarget as HTMLButtonElement).style.borderColor = "var(--th-accent)"; (e.currentTarget as HTMLButtonElement).style.color = "var(--th-accent)"; }}
                  onMouseLeave={(e) => { (e.currentTarget as HTMLButtonElement).style.borderColor = "var(--th-border)"; (e.currentTarget as HTMLButtonElement).style.color = "var(--th-text-secondary)"; }}
                >
                  <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><circle cx="18" cy="18" r="3"/><circle cx="6" cy="6" r="3"/><circle cx="6" cy="18" r="3"/><path d="M6 9v6M9 6h6a3 3 0 010 6h-6"/></svg>
                  <div style={{ textAlign: "left" }}>
                    <div style={{ fontWeight: 700 }}>{t({ ko: "Git 저장소 가져오기", en: "Import from Git", ja: "Gitリポジトリのインポート", zh: "从 Git 导入" })}</div>
                    <div style={{ fontSize: "10px", color: "var(--th-text-muted)", marginTop: 2 }}>
                      {t({ ko: "GitHub · GitLab — URL로 클론 후 프로젝트 자동 생성", en: "GitHub · GitLab — clone by URL and auto-create project", ja: "GitHub · GitLab — URLでクローンして自動作成", zh: "GitHub · GitLab — 通过 URL 克隆并自动创建项目" })}
                    </div>
                  </div>
                  <span style={{ marginLeft: "auto", fontSize: "14px", color: "var(--th-text-muted)" }}>→</span>
                </button>
              </div>
            </>
          )}

          {/* ── STEP 2: 디렉티브 편집 ── */}
          {step === "directive" && (
            <DirectiveEditorStep
              directive={directive}
              directiveTypeSlug={directiveTypeSlug}
              templates={directiveTemplates}
              onDirectiveChange={setDirective}
              onTemplateLoad={(tpl) => {
                setDirective(tpl.template);
                setDirectiveTypeSlug(tpl.slug);
              }}
              t={t}
            />
          )}

          {/* ── STEP 3: 기본 정보 ── */}
          {step === "info" && (
            <div className="space-y-4">
              {selectedCategory ? (
                <div className="flex items-center gap-2 px-3 py-2 text-xs" style={{ borderRadius: 0, border: `1px solid ${selectedCategory.color}44`, background: `${selectedCategory.color}11` }}>
                  <span className="font-semibold" style={{ color: selectedCategory.color }}>
                    {t({ ko: "유형:", en: "Type:", ja: "タイプ:", zh: "类型：" })} {categoryDisplayName(selectedCategory)}
                  </span>
                  <button onClick={() => setStep("category")} className="ml-auto text-[10px] underline" style={{ color: "var(--th-text-muted)" }}>
                    {t({ ko: "변경", en: "Change", ja: "変更", zh: "更改" })}
                  </button>
                </div>
              ) : (
                <div className="flex items-center gap-2 px-3 py-2 text-xs" style={{ borderRadius: 0, border: "1px solid var(--th-border)", color: "var(--th-text-muted)" }}>
                  {t({ ko: "유형 없이 시작", en: "No type selected", ja: "タイプなし", zh: "无类型" })}
                  <button onClick={() => setStep("category")} className="ml-auto text-[10px] underline" style={{ color: "var(--th-text-muted)" }}>
                    {t({ ko: "변경", en: "Change", ja: "変更", zh: "更改" })}
                  </button>
                </div>
              )}

              <FormField
                label={t({ ko: "프로젝트 이름", en: "Project name", ja: "プロジェクト名", zh: "项目名称" })}
                required
                error={submitted && !projectName.trim() ? t({ ko: "프로젝트 이름을 입력해주세요.", en: "Please enter a project name.", ja: "プロジェクト名を入力してください。", zh: "请输入项目名称。" }) : undefined}
              >
                <Input
                  autoFocus
                  value={projectName}
                  onChange={(e) => setProjectName(e.target.value)}
                  placeholder={t({ ko: "예: 쇼핑몰 앱 개발 2026", en: "e.g. Shopping App 2026", ja: "例: ショッピングアプリ 2026", zh: "例如：电商应用 2026" })}
                  error={submitted && !projectName.trim()}
                />
              </FormField>

              <FormField
                label={t({ ko: "프로젝트 경로", en: "Project path", ja: "プロジェクトパス", zh: "项目路径" })}
                required
                hint={t({ ko: "AI 에이전트가 실행될 로컬 폴더 경로", en: "Local folder where the AI agent will run", ja: "AIエージェントが実行されるフォルダ", zh: "AI 代理运行的本地文件夹" })}
                error={submitted && !projectPath.trim() ? t({ ko: "프로젝트 경로는 필수입니다.", en: "Project path is required.", ja: "パスは必須です。", zh: "路径为必填项。" }) : undefined}
              >
                <div className="flex items-stretch gap-2">
                  <div className="flex-1">
                    <Input
                      value={projectPath}
                      onChange={(e) => handlePathChange(e.target.value)}
                      placeholder="/Users/me/projects/my-app"
                      error={submitted && !projectPath.trim()}
                    />
                  </div>
                  {!pathTools.pathApiUnsupported && (
                    <button
                      type="button"
                      onClick={() => void handleOpenBrowser()}
                      style={{ padding: "0 10px", borderRadius: 0, border: "1px solid var(--th-border)", background: "var(--th-bg-surface)", color: "var(--th-text-secondary)", ...mono, fontSize: "0.7rem", cursor: "pointer", whiteSpace: "nowrap", flexShrink: 0 }}
                    >
                      {t({ ko: "탐색", en: "Browse", ja: "参照", zh: "浏览" })}
                    </button>
                  )}
                </div>
                {pathAutoGenerated && projectPath && (
                  <p className="mt-1 text-[10px] font-mono" style={{ color: "var(--th-text-muted)" }}>
                    {t({ ko: "자동 생성됨 · 직접 수정 가능", en: "Auto-generated · edit to change", ja: "自動生成済み · 編集で変更可", zh: "自动生成 · 可直接编辑" })}
                  </p>
                )}
                {pathTools.pathApiUnsupported && (
                  <p className="mt-1 text-[10px] font-mono" style={{ color: "var(--th-text-muted)" }}>{pathTools.unsupportedPathApiMessage}</p>
                )}
                {pathTools.formFeedback && (
                  <p className="mt-1 text-[10px] font-mono" style={{ color: pathTools.formFeedback.tone === "error" ? "var(--th-danger-text)" : "var(--th-text-muted)" }}>
                    {pathTools.formFeedback.message}
                  </p>
                )}
              </FormField>

              <FormField
                label={t({ ko: "한 줄 목표", en: "One-line goal", ja: "一言ゴール", zh: "一句话目标" })}
                suffix={t({ ko: "(선택)", en: "(optional)", ja: "(任意)", zh: "（可选）" })}
              >
                <Input
                  value={coreGoal}
                  onChange={(e) => setCoreGoal(e.target.value)}
                  onKeyDown={(e) => { if (e.key === "Enter" && canConfirmInfo) setStep("agent"); }}
                  placeholder={t({ ko: "예: 2026년 Q2 출시를 위한 신규 기능 개발", en: "e.g. New feature development for Q2 2026", ja: "例: Q2リリースに向けた新機能開発", zh: "例如：Q2 发布的新功能开发" })}
                />
              </FormField>

              {selectedCategory?.slug === "design" && (
                figmaConnected === false ? (
                  <div className="flex items-center justify-between gap-3 px-3 py-2.5 text-xs font-mono" style={{ border: "1px solid rgba(242,78,30,0.4)", background: "rgba(242,78,30,0.06)", borderRadius: 0 }}>
                    <span style={{ color: "var(--th-text-secondary)" }}>
                      {t({ ko: "Figma가 연결되지 않았습니다.", en: "Figma is not connected.", ja: "Figmaが接続されていません。", zh: "Figma 未连接。" })}
                    </span>
                    <button
                      type="button"
                      onClick={() => { onClose(); openWindow("settings"); }}
                      className="shrink-0 px-2.5 py-1 text-[11px] font-semibold transition"
                      style={{ borderRadius: 0, border: "1px solid rgba(242,78,30,0.5)", color: "#f24e1e", background: "transparent", cursor: "pointer" }}
                    >
                      {t({ ko: "설정에서 연결 →", en: "Connect in Settings →", ja: "設定で接続 →", zh: "前往设置连接 →" })}
                    </button>
                  </div>
                ) : figmaConnected === true ? (
                  <FormField
                    label={t({ ko: "Figma 디자인 URL", en: "Figma Design URL", ja: "Figma URL", zh: "Figma 设计 URL" })}
                    suffix={t({ ko: "(선택)", en: "(optional)", ja: "(任意)", zh: "（可选）" })}
                    hint={t({ ko: "프로젝트 전체 기본값 — 태스크별 URL로 덮어쓰기 가능", en: "Project-wide default — can be overridden per task", ja: "プロジェクト全体のデフォルト — タスク毎に上書き可", zh: "项目默认值 — 可在任务级别覆盖" })}
                  >
                    <Input
                      value={figmaUrl}
                      onChange={(e) => setFigmaUrl(e.target.value)}
                      placeholder="https://www.figma.com/design/..."
                    />
                  </FormField>
                ) : (
                  <div className="px-3 py-2 text-xs font-mono" style={{ color: "var(--th-text-muted)" }}>
                    {t({ ko: "Figma 연결 상태 확인 중…", en: "Checking Figma connection…", ja: "Figma接続確認中…", zh: "检查 Figma 连接中…" })}
                  </div>
                )
              )}
            </div>
          )}

          {/* ── STEP 4: 역할 배정 ── */}
          {step === "agent" && (() => {
            const ROLE_DEFS: { key: "pm" | "pl" | "dev"; badge: string; label: string; desc: string }[] = [
              { key: "pm", badge: "PM", label: t({ ko: "Project Manager", en: "Project Manager", ja: "プロジェクトマネージャー", zh: "项目经理" }), desc: t({ ko: "전체 일정·예산·리스크 관리", en: "Schedule, budget & risk management", ja: "スケジュール・予算・リスク管理", zh: "进度、预算和风险管理" }) },
              { key: "pl", badge: "PL", label: t({ ko: "Project Lead", en: "Project Lead", ja: "プロジェクトリード", zh: "项目负责人" }), desc: t({ ko: "기술 방향·아키텍처 결정", en: "Tech direction & architecture", ja: "技術方向・アーキテクチャ", zh: "技术方向和架构决策" }) },
              { key: "dev", badge: "Dev", label: t({ ko: "Developer", en: "Developer", ja: "デベロッパー", zh: "开发者" }), desc: t({ ko: "기능 구현·코드 작성", en: "Feature implementation & coding", ja: "機能実装・コーディング", zh: "功能实现和代码编写" }) },
            ];
            return (
              <div className="space-y-3">
                <p style={{ ...mono, fontSize: "11px", color: "var(--th-text-secondary)" }}>
                  {t({ ko: "PM · PL · Dev 3명을 필수로 배정해주세요.", en: "Assign PM · PL · Dev — all three are required.", ja: "PM · PL · Dev の3名を必ず配置してください。", zh: "请分配 PM · PL · Dev，三者均为必填。" })}
                </p>

                {cliAgents.length === 0 ? (
                  <div className="py-8 text-center" style={{ border: "1px dashed var(--th-border)", ...mono, fontSize: "11px", color: "var(--th-text-muted)" }}>
                    <p>$ ls agents/ --cli-only</p>
                    <p style={{ marginTop: 4, opacity: 0.6 }}>(empty)</p>
                    <p style={{ marginTop: 8, fontSize: "10px" }}>
                      {t({ ko: "CLI 에이전트가 없습니다. 에이전트 관리에서 CLI 도구를 설정하세요.", en: "No CLI agents. Configure a CLI provider in Agent Manager.", ja: "CLIエージェントがありません。", zh: "没有 CLI 代理。" })}
                    </p>
                  </div>
                ) : (
                  ROLE_DEFS.map(({ key, badge, label, desc }) => {
                    const assignedId = roleAssignments[key];
                    const assignedAgent = cliAgents.find((a) => a.id === assignedId);
                    const isOpen = selectedRoleSlot === key;
                    const missing = submitted && !assignedId;
                    return (
                      <div key={key}>
                        {/* Role slot row */}
                        <div
                          className="flex items-center gap-3 px-3 py-2.5"
                          style={{
                            border: `1px solid ${missing ? "rgba(251,113,133,0.5)" : assignedId ? "var(--th-accent)" : "var(--th-border)"}`,
                            background: assignedId ? "rgba(245,158,11,0.06)" : "var(--th-bg-surface)",
                            borderBottom: isOpen ? "none" : undefined,
                          }}
                        >
                          {/* Badge */}
                          <span style={{
                            ...mono, fontSize: "9px", fontWeight: 700, padding: "2px 7px", flexShrink: 0,
                            background: assignedId ? "var(--th-accent)" : missing ? "rgba(251,113,133,0.15)" : "var(--th-bg-elevated)",
                            color: assignedId ? "var(--th-accent-text)" : missing ? "#fb7185" : "var(--th-text-muted)",
                            border: `1px solid ${assignedId ? "var(--th-accent)" : missing ? "rgba(251,113,133,0.4)" : "var(--th-border)"}`,
                          }}>
                            {badge}
                          </span>
                          {/* Content */}
                          <div className="flex-1 min-w-0">
                            {assignedAgent ? (
                              <div className="flex items-center gap-2 flex-wrap">
                                {/* Agent avatar: SVG bot icon */}
                                <svg width="16" height="16" viewBox="0 0 16 16" fill="none" style={{ flexShrink: 0, color: "var(--th-accent)" }}>
                                  <rect x="3" y="5" width="10" height="8" rx="2" stroke="currentColor" strokeWidth="1.4"/>
                                  <circle cx="6" cy="9" r="1" fill="currentColor"/>
                                  <circle cx="10" cy="9" r="1" fill="currentColor"/>
                                  <path d="M6 4V3" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round"/>
                                  <path d="M10 4V3" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round"/>
                                  <path d="M6 13v1M10 13v1" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round"/>
                                </svg>
                                <span style={{ ...mono, fontSize: "12px", fontWeight: 600, color: "var(--th-accent)" }}>
                                  {assignedAgent.name_ko || assignedAgent.name}
                                </span>
                                {assignedAgent.department && (
                                  <span style={{ ...mono, fontSize: "9px", color: "var(--th-text-muted)" }}>
                                    {assignedAgent.department.name_ko ?? assignedAgent.department.name}
                                  </span>
                                )}
                                <span style={{ ...mono, fontSize: "9px", color: "var(--th-text-muted)", opacity: 0.6 }}>
                                  {PROVIDER_LABEL[assignedAgent.cli_provider] ?? assignedAgent.cli_provider}
                                </span>
                              </div>
                            ) : (
                              <div>
                                <span style={{ ...mono, fontSize: "11px", fontWeight: 600, color: missing ? "#fb7185" : "var(--th-text-secondary)" }}>{label}</span>
                                <span style={{ ...mono, fontSize: "10px", color: "var(--th-text-muted)", marginLeft: 6 }}>{desc}</span>
                              </div>
                            )}
                          </div>
                          {/* Toggle button */}
                          <button
                            type="button"
                            onClick={() => setSelectedRoleSlot(isOpen ? null : key)}
                            className="flex items-center gap-1"
                            style={{
                              ...mono, fontSize: "9px", padding: "3px 8px", flexShrink: 0,
                              border: `1px solid ${isOpen ? "var(--th-accent)" : "var(--th-border)"}`,
                              background: isOpen ? "rgba(245,158,11,0.1)" : "transparent",
                              color: isOpen ? "var(--th-accent)" : "var(--th-text-muted)",
                              cursor: "pointer",
                            }}
                          >
                            {assignedId
                              ? t({ ko: "변경", en: "Change", ja: "変更", zh: "更改" })
                              : t({ ko: "선택", en: "Select", ja: "選択", zh: "选择" })}
                            <svg width="10" height="10" viewBox="0 0 10 10" fill="none" style={{ transform: isOpen ? "rotate(180deg)" : "none", transition: "transform 0.15s" }}>
                              <path d="M2 3.5L5 6.5L8 3.5" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round"/>
                            </svg>
                          </button>
                        </div>
                        {/* Inline agent picker */}
                        {isOpen && (
                          <div style={{ border: "1px solid var(--th-accent)", borderTop: "none", maxHeight: "200px", overflowY: "auto", background: "var(--th-bg-elevated)" }}>
                            {cliAgents.map((agent) => {
                              const isCurrent = agent.id === assignedId;
                              return (
                                <button
                                  key={agent.id}
                                  type="button"
                                  onClick={() => {
                                    setRoleAssignments((prev) => ({ ...prev, [key]: agent.id }));
                                    setSelectedRoleSlot(null);
                                  }}
                                  className="w-full flex items-center gap-3 px-3 py-2"
                                  style={{
                                    borderBottom: "1px solid var(--th-border)",
                                    background: isCurrent ? "rgba(245,158,11,0.1)" : "transparent",
                                    cursor: "pointer",
                                    textAlign: "left",
                                  }}
                                >
                                  {/* Agent avatar SVG */}
                                  <svg width="16" height="16" viewBox="0 0 16 16" fill="none" style={{ flexShrink: 0, color: isCurrent ? "var(--th-accent)" : "var(--th-text-muted)" }}>
                                    <rect x="3" y="5" width="10" height="8" rx="2" stroke="currentColor" strokeWidth="1.4"/>
                                    <circle cx="6" cy="9" r="1" fill="currentColor"/>
                                    <circle cx="10" cy="9" r="1" fill="currentColor"/>
                                    <path d="M6 4V3" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round"/>
                                    <path d="M10 4V3" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round"/>
                                    <path d="M6 13v1M10 13v1" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round"/>
                                  </svg>
                                  <div className="flex-1 min-w-0">
                                    <div className="flex items-center gap-2 flex-wrap">
                                      <span style={{ ...mono, fontSize: "12px", fontWeight: 600, color: isCurrent ? "var(--th-accent)" : "var(--th-text-heading)" }}>
                                        {agent.name_ko || agent.name}
                                      </span>
                                      <span style={{ ...mono, fontSize: "9px", color: "var(--th-text-muted)" }}>
                                        {PROVIDER_LABEL[agent.cli_provider] ?? agent.cli_provider}
                                      </span>
                                      {agent.role && (
                                        <span style={{ ...mono, fontSize: "9px", color: "var(--th-text-muted)", opacity: 0.6 }}>
                                          {agent.role.replace("_", " ").toUpperCase()}
                                        </span>
                                      )}
                                    </div>
                                    {agent.department && (
                                      <span style={{ ...mono, fontSize: "10px", color: "var(--th-text-muted)" }}>
                                        {agent.department.name_ko ?? agent.department.name}
                                      </span>
                                    )}
                                  </div>
                                  {/* Checkmark SVG for current selection */}
                                  {isCurrent && (
                                    <svg width="14" height="14" viewBox="0 0 14 14" fill="none" style={{ flexShrink: 0, color: "var(--th-accent)" }}>
                                      <path d="M2.5 7L5.5 10L11.5 4" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"/>
                                    </svg>
                                  )}
                                </button>
                              );
                            })}
                          </div>
                        )}
                      </div>
                    );
                  })
                )}

                {submitted && !canConfirmAgent && (
                  <div className="flex items-center gap-2" style={{ ...mono, fontSize: "10px", color: "#fb7185", border: "1px solid rgba(251,113,133,0.4)", padding: "6px 10px", background: "rgba(251,113,133,0.08)" }}>
                    {/* Warning SVG */}
                    <svg width="13" height="13" viewBox="0 0 13 13" fill="none" style={{ flexShrink: 0 }}>
                      <path d="M6.5 1L12 11.5H1L6.5 1Z" stroke="#fb7185" strokeWidth="1.3" strokeLinejoin="round"/>
                      <path d="M6.5 5v3" stroke="#fb7185" strokeWidth="1.4" strokeLinecap="round"/>
                      <circle cx="6.5" cy="9.5" r="0.6" fill="#fb7185"/>
                    </svg>
                    {t({ ko: "PM · PL · Dev 역할을 모두 배정해야 프로젝트를 시작할 수 있습니다.", en: "Assign PM, PL, and Dev roles to start the project.", ja: "PM · PL · Dev の全役割を配置してください。", zh: "必须配置 PM、PL 和 Dev 角色才能创建项目。" })}
                  </div>
                )}
              </div>
            );
          })()}
        </ModalBody>

        <ModalFooter className="justify-between">
          {/* Left: Back buttons */}
          {step === "github" ? null : step === "category" ? (
            <Button variant="ghost" size="sm" onClick={() => { setSelectedCategoryId(null); setDirective(""); setDirectiveTypeSlug(null); setStep("directive"); }}>
              {t({ ko: "유형 없이 시작하기", en: "Start without type", ja: "タイプなしで開始", zh: "不选类型继续" })}
            </Button>
          ) : step === "directive" ? (
            <Button variant="ghost" size="sm" onClick={() => setStep("category")}>
              {t({ ko: "← 이전", en: "← Back", ja: "← 戻る", zh: "← 上一步" })}
            </Button>
          ) : step === "info" ? (
            <Button variant="ghost" size="sm" onClick={() => setStep("directive")}>
              {t({ ko: "← 이전", en: "← Back", ja: "← 戻る", zh: "← 上一步" })}
            </Button>
          ) : (
            <Button variant="ghost" size="sm" onClick={() => setStep("info")}>
              {t({ ko: "← 이전", en: "← Back", ja: "← 戻る", zh: "← 上一步" })}
            </Button>
          )}

          {/* Right: Next/Confirm buttons */}
          {step === "github" ? null : step === "category" ? (
            <div className="flex items-center gap-3">
              {!selectedCategoryId && (
                <span style={{ ...mono, fontSize: "10px", color: "var(--th-text-muted)" }}>
                  {t({ ko: "유형 선택 후 진행", en: "Select a type to continue", ja: "タイプを選択してから次へ", zh: "请先选择类型" })}
                </span>
              )}
              <Button variant="primary" size="sm" onClick={() => setStep("directive")} disabled={!selectedCategoryId}>
                {t({ ko: "다음 →", en: "Next →", ja: "次へ →", zh: "下一步 →" })}
              </Button>
            </div>
          ) : step === "directive" ? (
            <Button variant="primary" size="sm" onClick={() => setStep("info")}>
              {t({ ko: "다음 →", en: "Next →", ja: "次へ →", zh: "下一步 →" })}
            </Button>
          ) : step === "info" ? (
            <Button variant="primary" size="sm" onClick={() => setStep("agent")} disabled={!canConfirmInfo}>
              {t({ ko: "다음 →", en: "Next →", ja: "次へ →", zh: "下一步 →" })}
            </Button>
          ) : (
            <Button variant="primary" size="sm" onClick={handleConfirm} disabled={busy || !canConfirmAgent}>
              {busy
                ? t({ ko: "생성 중…", en: "Creating…", ja: "作成中…", zh: "创建中…" })
                : t({ ko: "프로젝트 시작!", en: "Start Project!", ja: "プロジェクト開始!", zh: "开始项目!" })}
            </Button>
          )}
        </ModalFooter>
      </Modal>

      <ManualPathPickerDialog
        open={pathTools.manualPathPickerOpen}
        t={t}
        manualPathCurrent={pathTools.manualPathCurrent}
        manualPathParent={pathTools.manualPathParent}
        manualPathEntries={pathTools.manualPathEntries}
        manualPathLoading={pathTools.manualPathLoading}
        manualPathError={pathTools.manualPathError}
        manualPathTruncated={pathTools.manualPathTruncated}
        onClose={() => pathTools.setManualPathPickerOpen(false)}
        onLoadEntries={pathTools.loadManualPathEntries}
        onSelectCurrent={handlePathSelected}
      />
    </>
  );
}
