import { useCallback, useEffect, useRef, useState } from "react";
import type { Agent, Category } from "../../types";
import { Button, Input, FormField } from "../ui";
import AppWindow from "../windows/AppWindow";
import ManualPathPickerDialog from "../project-manager/ManualPathPickerDialog";
import { useProjectManagerPathTools } from "../project-manager/useProjectManagerPathTools";
import CategorySelectStep from "./CategorySelectStep";
import DirectiveEditorStep from "./DirectiveEditorStep";
import GitImportPanel from "../git-import/GitImportPanel";
import { useI18n } from "../../i18n";
/** Stub — Synapse/Figma API removed; Figma integration is no longer available */
const getFigmaInfo = (): Promise<{ connected: boolean }> => Promise.resolve({ connected: false });
import { fetchDirectiveTemplates, type DirectiveTemplateItem } from "../../api/organization-projects";
import { autoAssignAgents } from "../../api/project-kickoff";
import { fetchProjectTypeTemplates, type ProjectTypeTemplate } from "../../api/project-type-templates";
import { useUiStore } from "../../store/uiStore";

export type ProjectRoleAssignment = { role: string; agentId: string };
export type ProjectRoleAssignments = ProjectRoleAssignment[];

/** Internal state type — agentId can be null until assigned */
type RoleSlot = { role: string; agentId: string | null };

interface ProjectCreateModalProps {
  categories: Category[];
  agents: Agent[];
  onConfirm: (params: { name: string; categoryId: string | null; project_path: string; core_goal?: string; agentIds: string[]; roleAssignments: ProjectRoleAssignments; figma_url?: string | null; directive?: string | null; directive_type_slug?: string | null }) => void;
  onGitHubComplete?: (projectId: string) => void;
  onClose: () => void;
}

type Step = "category" | "directive" | "info" | "agent" | "github";
const ORDERED_STEPS: Step[] = ["category", "directive", "info", "agent"];

const CLI_PROVIDERS = new Set(["claude", "codex", "gemini", "opencode", "copilot", "antigravity", "cursor", "ollama"]);

const PROVIDER_LABEL: Record<string, string> = {
  claude: "Claude Code",
  codex: "Codex CLI",
  gemini: "Gemini CLI",
  opencode: "OpenCode",
  copilot: "Copilot",
  antigravity: "Antigravity",
  cursor: "Cursor",
  ollama: "Ollama",
};

/* ── Step titles — one inspiring line per step ── */
const STEP_META: Record<Step, { title: { ko: string; en: string; ja: string; zh: string }; sub: { ko: string; en: string; ja: string; zh: string } }> = {
  category: {
    title: { ko: "어떤 프로젝트인가요?", en: "What are you building?", ja: "何を作りますか？", zh: "你在构建什么？" },
    sub: { ko: "유형을 선택하면 최적의 워크플로우가 준비됩니다", en: "Choose a type and we'll set up the perfect workflow", ja: "タイプを選ぶと最適なワークフローが準備されます", zh: "选择类型，我们将设置最佳工作流程" },
  },
  directive: {
    title: { ko: "에이전트에게 방향을 알려주세요", en: "Guide your agents", ja: "エージェントに方向を示す", zh: "指导你的代理" },
    sub: { ko: "이 내용이 에이전트의 프롬프트에 주입됩니다", en: "This will be injected into every agent prompt", ja: "この内容がエージェントのプロンプトに注入されます", zh: "这将注入到每个代理的提示中" },
  },
  info: {
    title: { ko: "프로젝트를 정의하세요", en: "Define your project", ja: "プロジェクトを定義する", zh: "定义你的项目" },
    sub: { ko: "이름, 경로, 목표", en: "Name, path, and goal", ja: "名前、パス、ゴール", zh: "名称、路径和目标" },
  },
  agent: {
    title: { ko: "팀을 구성하세요", en: "Assemble your team", ja: "チームを編成する", zh: "组建你的团队" },
    sub: { ko: "에이전트에게 역할을 배정하세요", en: "Assign roles to your agents", ja: "エージェントに役割を割り当てる", zh: "为代理分配角色" },
  },
  github: {
    title: { ko: "Git 저장소 가져오기", en: "Import from Git", ja: "Gitからインポート", zh: "从 Git 导入" },
    sub: { ko: "", en: "", ja: "", zh: "" },
  },
};

export default function ProjectCreateModal({ categories, agents, onConfirm, onGitHubComplete, onClose }: ProjectCreateModalProps) {
  const [step, setStep] = useState<Step>("category");
  const [selectedCategoryId, setSelectedCategoryId] = useState<string | null>(null);
  const [projectName, setProjectName] = useState("");
  const [projectPath, setProjectPath] = useState("");
  const [coreGoal, setCoreGoal] = useState("");
  const [roleSlots, setRoleSlots] = useState<RoleSlot[]>([
    { role: "PM", agentId: null },
    { role: "PL", agentId: null },
    { role: "Dev", agentId: null },
  ]);
  const [openSlotIdx, setOpenSlotIdx] = useState<number | null>(null);
  const [figmaUrl, setFigmaUrl] = useState("");
  const [figmaConnected, setFigmaConnected] = useState<boolean | null>(null);
  const [submitted, setSubmitted] = useState(false);
  const [busy, setBusy] = useState(false);
  const [autoAssignBusy, setAutoAssignBusy] = useState(false);
  const [pathAutoGenerated, setPathAutoGenerated] = useState(false);
  const [directive, setDirective] = useState("");
  const [directiveTypeSlug, setDirectiveTypeSlug] = useState<string | null>(null);
  const [directiveTemplates, setDirectiveTemplates] = useState<DirectiveTemplateItem[]>([]);
  const [customTypes, setCustomTypes] = useState<ProjectTypeTemplate[]>([]);
  const autoAdvanceTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    fetchDirectiveTemplates().then(setDirectiveTemplates).catch(() => {});
    fetchProjectTypeTemplates().then(setCustomTypes).catch(() => {});
  }, []);

  const { t, language } = useI18n();
  const { openWindow } = useUiStore();

  /* ── 기존 categories + 커스텀 유형 합치기 ── */
  const customAsCategories: Category[] = customTypes.map((ct) => ({
    id: `custom_${ct.id}`,
    name: ct.name,
    name_ko: ct.name_ko,
    slug: `custom-${ct.id}`,
    description: ct.description,
    icon: "custom",
    color: "#6366f1",
    kpi_schema: "{}",
    risk_schema: "{}",
    gate_schema: "{}",
    deliverable_schema: "{}",
    is_template: 0,
    version: 1,
    owner_scope: "org" as const,
    created_at: ct.created_at,
    updated_at: ct.updated_at,
  }));
  const allCategories = [...customAsCategories, ...categories];

  const pathTools = useProjectManagerPathTools({
    t,
    projectPath,
    pathToolsVisible: step === "info",
  });

  const cliAgents = agents.filter((a) => CLI_PROVIDERS.has(a.cli_provider));

  const handlePathChange = (value: string) => {
    setProjectPath(value);
  };

  const handleCategorySelect = (id: string) => {
    setSelectedCategoryId(id);

    /* 커스텀 유형 선택 */
    if (id.startsWith("custom_")) {
      const ctId = id.replace("custom_", "");
      const ct = customTypes.find((c) => c.id === ctId);
      if (ct?.default_directive) {
        setDirective(ct.default_directive);
        setDirectiveTypeSlug(null);
      }
      if (autoAdvanceTimer.current) clearTimeout(autoAdvanceTimer.current);
      autoAdvanceTimer.current = setTimeout(() => setStep("directive"), 300);
      return;
    }

    /* 기존 카테고리 선택 */
    const cat = categories.find((c) => c.id === id);
    if (cat?.slug === "design") {
      setFigmaConnected(null);
      getFigmaInfo().then((info) => setFigmaConnected(info.connected)).catch(() => setFigmaConnected(false));
    }
    const tpl = directiveTemplates.find((t) => cat?.slug === t.slug);
    if (tpl) {
      setDirective(tpl.template);
      setDirectiveTypeSlug(tpl.slug);
    }
    if (autoAdvanceTimer.current) clearTimeout(autoAdvanceTimer.current);
    autoAdvanceTimer.current = setTimeout(() => setStep("directive"), 300);
  };

  const handleOpenBrowser = useCallback(async () => {
    pathTools.setManualPathPickerOpen(true);
    await pathTools.loadManualPathEntries(undefined);
  }, [pathTools]);

  const handlePathSelected = useCallback(() => {
    if (pathTools.manualPathCurrent) {
      setProjectPath(pathTools.manualPathCurrent);
      setPathAutoGenerated(false);
    }
    pathTools.setManualPathPickerOpen(false);
  }, [pathTools]);

  const selectedCategory = allCategories.find((c) => c.id === selectedCategoryId) ?? null;
  const canConfirmInfo = projectName.trim().length > 0 && projectPath.trim().length > 0;
  const canConfirmAgent = roleSlots.some(s => s.agentId && s.role.trim().length > 0);

  const handleConfirm = () => {
    setSubmitted(true);
    if (!canConfirmInfo || !canConfirmAgent) return;
    setBusy(true);
    const roleAssignments: ProjectRoleAssignment[] = roleSlots
      .filter((s): s is ProjectRoleAssignment => s.agentId !== null && s.role.trim().length > 0)
      .map(s => ({ role: s.role.trim(), agentId: s.agentId }));
    const agentIds = Array.from(new Set(roleAssignments.map(r => r.agentId)));
    /* 커스텀 유형은 categories 테이블에 없으므로 categoryId를 null로 전달 */
    const realCategoryId = selectedCategoryId?.startsWith("custom_") ? null : selectedCategoryId;
    onConfirm({
      name: projectName.trim(),
      categoryId: realCategoryId,
      project_path: projectPath.trim(),
      core_goal: coreGoal.trim() || (selectedCategory ? `${selectedCategory.name_ko ?? selectedCategory.name} 프로젝트` : undefined),
      agentIds,
      roleAssignments,
      figma_url: figmaUrl.trim() || null,
      directive: directive.trim() || null,
      directive_type_slug: directiveTypeSlug,
    });
  };

  const categoryDisplayName = (cat: Category) => language === "ko" ? cat.name_ko ?? cat.name : cat.name;

  /* ── Navigation helpers ── */
  const stepIdx = ORDERED_STEPS.indexOf(step);
  const goNext = () => {
    if (step === "category") setStep("directive");
    else if (step === "directive") setStep("info");
    else if (step === "info" && canConfirmInfo) setStep("agent");
    else if (step === "agent") handleConfirm();
  };
  const goBack = () => {
    if (step === "directive") setStep("category");
    else if (step === "info") setStep("directive");
    else if (step === "agent") setStep("info");
  };

  const display: React.CSSProperties = { fontFamily: "var(--th-font-display)" };
  const mono: React.CSSProperties = { fontFamily: "var(--th-font-mono)" };

  const windowIcon = (
    <svg viewBox="0 0 18 18" fill="none" stroke="#3B82F6" strokeWidth={1.4} strokeLinecap="round" strokeLinejoin="round" width={16} height={16}>
      <path d="M9 1.5v15M1.5 9h15" />
      <rect x="2" y="2" width="14" height="14" rx="3" />
    </svg>
  );

  return (
    <>
      <AppWindow
        windowType="project-create"
        title={t(STEP_META[step].title)}
        emoji={windowIcon}
        defaultWidth={580}
        defaultHeight={680}
        onClose={onClose}
      >
        {/* ── Step header — title + subtitle + dot indicator ── */}
        <div style={{ padding: "20px 24px 0 24px" }}>
          {/* Step title */}
          <h2 style={{
            ...display,
            fontSize: "20px",
            fontWeight: 700,
            color: "#111827",
            lineHeight: 1.3,
            margin: 0,
          }}>
            {t(STEP_META[step].title)}
          </h2>
          {STEP_META[step].sub[language] && (
            <p style={{
              fontSize: "12px",
              color: "#9CA3AF",
              marginTop: 6,
              lineHeight: 1.5,
            }}>
              {t(STEP_META[step].sub)}
            </p>
          )}

          {/* Dot progress indicator */}
          {step !== "github" && (
            <div className="flex items-center gap-2" style={{ marginTop: 20 }}>
              {ORDERED_STEPS.map((s, i) => (
                <button
                  key={s}
                  type="button"
                  onClick={() => {
                    if (s === "agent" && !canConfirmInfo) return;
                    if (s !== "github") setStep(s);
                  }}
                  style={{
                    width: i === stepIdx ? 24 : 8,
                    height: 8,
                    border: "none",
                    background: i === stepIdx ? "#3B82F6" : i < stepIdx ? "#3B82F6" : "#E5E7EB",
                    opacity: i <= stepIdx ? 1 : 0.4,
                    cursor: "pointer",
                    padding: 0,
                    transition: "all 0.3s ease",
                  }}
                />
              ))}
              <span style={{
                ...mono,
                fontSize: "10px",
                color: "#9CA3AF",
                marginLeft: 8,
              }}>
                {stepIdx + 1}/{ORDERED_STEPS.length}
              </span>
            </div>
          )}
        </div>

        <div className="flex-1 overflow-y-auto p-5" style={{ fontFamily: "var(--th-font-mono)" }}>
          <div style={{ minHeight: 280 }}>
            {/* ── GitHub Import ── */}
            {step === "github" && (
              <GitImportPanel
                onComplete={({ projectId }) => { onGitHubComplete?.(projectId); }}
                onCancel={() => setStep("category")}
              />
            )}

            {/* ── STEP 1: Category ── */}
            {step === "category" && (
              <div className="space-y-5">
                <CategorySelectStep
                  categories={allCategories}
                  selectedId={selectedCategoryId}
                  onSelect={handleCategorySelect}
                />
                {/* Git import entry */}
                <button
                  type="button"
                  onClick={() => setStep("github")}
                  className="w-full flex items-center gap-4 transition-colors"
                  style={{
                    padding: "14px 16px",
                    border: "1px dashed #E5E7EB",
                    background: "transparent",
                    color: "#6B7280",
                    cursor: "pointer",
                  }}
                  onMouseEnter={(e) => { e.currentTarget.style.borderColor = "#3B82F6"; e.currentTarget.style.color = "#3B82F6"; }}
                  onMouseLeave={(e) => { e.currentTarget.style.borderColor = "#E5E7EB"; e.currentTarget.style.color = "#6B7280"; }}
                >
                  <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><circle cx="18" cy="18" r="3"/><circle cx="6" cy="6" r="3"/><circle cx="6" cy="18" r="3"/><path d="M6 9v6M9 6h6a3 3 0 010 6h-6"/></svg>
                  <div style={{ textAlign: "left", flex: 1 }}>
                    <div style={{ ...display, fontWeight: 600, fontSize: "13px" }}>
                      {t({ ko: "Git 저장소 가져오기", en: "Import from Git", ja: "Gitリポジトリのインポート", zh: "从 Git 导入" })}
                    </div>
                    <div style={{ fontSize: "11px", color: "#9CA3AF", marginTop: 2 }}>
                      {t({ ko: "GitHub / GitLab URL로 클론 후 자동 생성", en: "Clone by URL and auto-create project", ja: "URLでクローンして自動作成", zh: "通过 URL 克隆并自动创建" })}
                    </div>
                  </div>
                  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" style={{ flexShrink: 0, opacity: 0.5 }}>
                    <path d="M5 12h14M12 5l7 7-7 7"/>
                  </svg>
                </button>
              </div>
            )}

            {/* ── STEP 2: Directive ── */}
            {step === "directive" && (
              <DirectiveEditorStep
                directive={directive}
                directiveTypeSlug={directiveTypeSlug}
                templates={directiveTemplates}
                onDirectiveChange={setDirective}
                onTemplateLoad={(tpl) => {
                  setDirective(tpl.template);
                  setDirectiveTypeSlug(tpl.slug);
                }}
                t={t}
              />
            )}

            {/* ── STEP 3: Project Info ── */}
            {step === "info" && (
              <div className="space-y-5">
                {selectedCategory && (
                  <div className="flex items-center gap-3" style={{
                    padding: "10px 14px",
                    background: `${selectedCategory.color}08`,
                    borderLeft: `3px solid ${selectedCategory.color}`,
                  }}>
                    <span style={{ ...display, fontSize: "12px", fontWeight: 600, color: selectedCategory.color }}>
                      {categoryDisplayName(selectedCategory)}
                    </span>
                    <button onClick={() => setStep("category")} style={{
                      marginLeft: "auto", ...mono, fontSize: "10px",
                      color: "#9CA3AF", background: "none", border: "none", cursor: "pointer",
                      textDecoration: "underline",
                    }}>
                      {t({ ko: "변경", en: "Change", ja: "変更", zh: "更改" })}
                    </button>
                  </div>
                )}

                <FormField
                  label={t({ ko: "프로젝트 이름", en: "Project name", ja: "プロジェクト名", zh: "项目名称" })}
                  required
                  error={submitted && !projectName.trim() ? t({ ko: "이름을 입력해주세요", en: "Please enter a name", ja: "名前を入力してください", zh: "请输入名称" }) : undefined}
                >
                  <Input
                    autoFocus
                    value={projectName}
                    onChange={(e) => setProjectName(e.target.value)}
                    placeholder={t({ ko: "쇼핑몰 앱 개발 2026", en: "Shopping App 2026", ja: "ショッピングアプリ 2026", zh: "电商应用 2026" })}
                    error={submitted && !projectName.trim()}
                  />
                </FormField>

                <FormField
                  label={t({ ko: "프로젝트 경로", en: "Project path", ja: "プロジェクトパス", zh: "项目路径" })}
                  required
                  hint={t({ ko: "AI 에이전트가 실행될 로컬 폴더", en: "Local folder where agents will work", ja: "エージェントが実行されるフォルダ", zh: "代理工作的本地文件夹" })}
                  error={submitted && !projectPath.trim() ? t({ ko: "경로를 입력해주세요", en: "Path is required", ja: "パスを入力してください", zh: "请输入路径" }) : undefined}
                >
                  <div className="flex items-stretch gap-2">
                    <div className="flex-1">
                      <Input
                        value={projectPath}
                        onChange={(e) => handlePathChange(e.target.value)}
                        placeholder="/Users/me/projects/my-app"
                        error={submitted && !projectPath.trim()}
                      />
                    </div>
                    {!pathTools.pathApiUnsupported && (
                      <button
                        type="button"
                        onClick={() => void handleOpenBrowser()}
                        style={{ padding: "0 12px", border: "1px solid #E5E7EB", background: "#F9FAFB", color: "#6B7280", ...mono, fontSize: "11px", cursor: "pointer", whiteSpace: "nowrap", flexShrink: 0 }}
                      >
                        {t({ ko: "탐색", en: "Browse", ja: "参照", zh: "浏览" })}
                      </button>
                    )}
                  </div>
                  {pathAutoGenerated && projectPath && (
                    <p className="mt-1" style={{ ...mono, fontSize: "10px", color: "#9CA3AF" }}>
                      {t({ ko: "자동 생성됨", en: "Auto-generated", ja: "自動生成済み", zh: "自动生成" })}
                    </p>
                  )}
                  {pathTools.pathApiUnsupported && (
                    <p className="mt-1" style={{ ...mono, fontSize: "10px", color: "#9CA3AF" }}>{pathTools.unsupportedPathApiMessage}</p>
                  )}
                  {pathTools.formFeedback && (
                    <p className="mt-1" style={{ ...mono, fontSize: "10px", color: pathTools.formFeedback.tone === "error" ? "#DC2626" : "#9CA3AF" }}>
                      {pathTools.formFeedback.message}
                    </p>
                  )}
                </FormField>

                <FormField
                  label={t({ ko: "한 줄 목표", en: "One-line goal", ja: "一言ゴール", zh: "一句话目标" })}
                  suffix={t({ ko: "(선택)", en: "(optional)", ja: "(任意)", zh: "（可选）" })}
                >
                  <Input
                    value={coreGoal}
                    onChange={(e) => setCoreGoal(e.target.value)}
                    onKeyDown={(e) => { if (e.key === "Enter" && canConfirmInfo) setStep("agent"); }}
                    placeholder={t({ ko: "2026년 Q2 출시 신규 기능 개발", en: "New feature for Q2 2026 launch", ja: "Q2リリースの新機能開発", zh: "Q2 发布的新功能开发" })}
                  />
                </FormField>

                {selectedCategory?.slug === "design" && (
                  figmaConnected === false ? (
                    <div className="flex items-center justify-between gap-3" style={{
                      padding: "12px 14px", borderLeft: "3px solid rgba(242,78,30,0.6)",
                      background: "rgba(242,78,30,0.04)", fontSize: "12px",
                    }}>
                      <span style={{ color: "#6B7280" }}>
                        {t({ ko: "Figma 미연결", en: "Figma not connected", ja: "Figma未接続", zh: "Figma 未连接" })}
                      </span>
                      <button
                        type="button"
                        onClick={() => { onClose(); openWindow("settings"); }}
                        style={{ ...mono, fontSize: "11px", color: "#f24e1e", background: "none", border: "none", cursor: "pointer", textDecoration: "underline" }}
                      >
                        {t({ ko: "설정에서 연결", en: "Connect in Settings", ja: "設定で接続", zh: "前往设置" })}
                      </button>
                    </div>
                  ) : figmaConnected === true ? (
                    <FormField
                      label={t({ ko: "Figma URL", en: "Figma URL", ja: "Figma URL", zh: "Figma URL" })}
                      suffix={t({ ko: "(선택)", en: "(optional)", ja: "(任意)", zh: "（可选）" })}
                    >
                      <Input
                        value={figmaUrl}
                        onChange={(e) => setFigmaUrl(e.target.value)}
                        placeholder="https://www.figma.com/design/..."
                      />
                    </FormField>
                  ) : (
                    <p style={{ ...mono, fontSize: "11px", color: "#9CA3AF", padding: "8px 0" }}>
                      {t({ ko: "Figma 연결 확인 중...", en: "Checking Figma...", ja: "Figma確認中...", zh: "检查 Figma..." })}
                    </p>
                  )
                )}
              </div>
            )}

            {/* ── STEP 4: Agent Assignment ── */}
            {step === "agent" && (() => {
              const handleAutoAssign = async () => {
                setAutoAssignBusy(true);
                try {
                  const result = await autoAssignAgents({
                    project_name: projectName.trim() || undefined,
                    core_goal: coreGoal.trim() || undefined,
                    category_name: selectedCategory ? (selectedCategory.name_ko ?? selectedCategory.name) : undefined,
                    directive: directive.trim() || undefined,
                  });
                  if (result.ok && result.assignments.length > 0) {
                    const newSlots: RoleSlot[] = result.assignments.map((a) => ({
                      role: a.role,
                      agentId: a.agent_id,
                    }));
                    setRoleSlots(newSlots);
                  } else {
                    // fallback: 인덱스 순서
                    setRoleSlots(prev => prev.map((slot, idx) => ({
                      ...slot,
                      agentId: cliAgents[idx]?.id ?? null,
                    })));
                  }
                } catch {
                  // fallback: 인덱스 순서
                  setRoleSlots(prev => prev.map((slot, idx) => ({
                    ...slot,
                    agentId: cliAgents[idx]?.id ?? null,
                  })));
                } finally {
                  setAutoAssignBusy(false);
                }
              };
              const handleAddSlot = () => {
                setRoleSlots(prev => [...prev, { role: "", agentId: null }]);
                setOpenSlotIdx(roleSlots.length);
              };
              const handleRemoveSlot = (idx: number) => {
                setRoleSlots(prev => prev.filter((_, i) => i !== idx));
                if (openSlotIdx === idx) setOpenSlotIdx(null);
                else if (openSlotIdx !== null && openSlotIdx > idx) setOpenSlotIdx(openSlotIdx - 1);
              };

              return (
                <div className="space-y-4">
                  {/* Auto-assign button */}
                  {cliAgents.length > 0 && (
                    <div className="flex justify-end">
                      <button
                        type="button"
                        onClick={handleAutoAssign}
                        disabled={autoAssignBusy}
                        style={{
                          ...mono, fontSize: "11px", padding: "6px 14px",
                          border: "1px solid #3B82F6",
                          background: "rgba(245,158,11,0.06)",
                          color: "#3B82F6",
                          cursor: autoAssignBusy ? "wait" : "pointer",
                          opacity: autoAssignBusy ? 0.6 : 1,
                          display: "flex", alignItems: "center", gap: 6,
                        }}
                      >
                        {autoAssignBusy && (
                          <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="animate-spin">
                            <path d="M21 12a9 9 0 1 1-6.219-8.56" />
                          </svg>
                        )}
                        {autoAssignBusy
                          ? t({ ko: "AI 분석 중...", en: "AI analyzing...", ja: "AI分析中...", zh: "AI分析中..." })
                          : t({ ko: "AI 자동 배정", en: "AI Auto-assign", ja: "AI自動配置", zh: "AI自动分配" })}
                      </button>
                    </div>
                  )}

                  {cliAgents.length === 0 ? (
                    <div style={{
                      padding: "40px 20px", textAlign: "center",
                      border: "1px dashed #E5E7EB",
                    }}>
                      <p style={{ ...display, fontSize: "14px", color: "#9CA3AF" }}>
                        {t({ ko: "CLI 에이전트가 없습니다", en: "No CLI agents found", ja: "CLIエージェントがありません", zh: "没有 CLI 代理" })}
                      </p>
                      <p style={{ ...mono, fontSize: "11px", color: "#9CA3AF", marginTop: 8, opacity: 0.6 }}>
                        {t({ ko: "에이전트 관리에서 CLI를 먼저 설정하세요", en: "Set up a CLI provider in Agent Manager first", ja: "先にエージェント管理でCLIを設定してください", zh: "请先在代理管理中设置 CLI" })}
                      </p>
                    </div>
                  ) : (
                    <div className="space-y-2">
                      {roleSlots.map((slot, idx) => {
                        const assignedAgent = cliAgents.find(a => a.id === slot.agentId);
                        const isOpen = openSlotIdx === idx;
                        const missing = submitted && !slot.agentId;
                        return (
                          <div key={idx}>
                            <div
                              className="flex items-center gap-3"
                              style={{
                                padding: "10px 14px",
                                border: `1.5px solid ${missing ? "rgba(251,113,133,0.5)" : slot.agentId ? "#3B82F6" : "#E5E7EB"}`,
                                background: slot.agentId ? "rgba(245,158,11,0.03)" : "#F9FAFB",
                                borderBottom: isOpen ? "none" : undefined,
                                transition: "border-color 0.2s, background 0.2s",
                              }}
                            >
                              {/* Editable role label */}
                              <input
                                value={slot.role}
                                onChange={e => setRoleSlots(prev => prev.map((s, i) => i === idx ? { ...s, role: e.target.value } : s))}
                                placeholder={t({ ko: "역할", en: "Role", ja: "役割", zh: "角色" })}
                                style={{
                                  ...mono, fontSize: "11px", fontWeight: 700,
                                  width: "60px", flexShrink: 0,
                                  padding: "4px 8px",
                                  textAlign: "center",
                                  background: slot.agentId ? "#3B82F6" : "#FFFFFF",
                                  color: slot.agentId ? "#FFFFFF" : "#9CA3AF",
                                  border: "none", outline: "none",
                                }}
                              />
                              {/* Agent info */}
                              <div className="flex-1 min-w-0">
                                {assignedAgent ? (
                                  <div className="flex items-center gap-2">
                                    <svg width="14" height="14" viewBox="0 0 16 16" fill="none" style={{ flexShrink: 0, color: "#3B82F6" }}>
                                      <rect x="3" y="5" width="10" height="8" rx="2" stroke="currentColor" strokeWidth="1.4"/>
                                      <circle cx="6" cy="9" r="1" fill="currentColor"/>
                                      <circle cx="10" cy="9" r="1" fill="currentColor"/>
                                      <path d="M6 4V3" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round"/>
                                      <path d="M10 4V3" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round"/>
                                    </svg>
                                    <span style={{ ...display, fontSize: "13px", fontWeight: 600, color: "#111827" }}>
                                      {assignedAgent.name_ko || assignedAgent.name}
                                    </span>
                                    <span style={{ ...mono, fontSize: "10px", color: "#9CA3AF" }}>
                                      {PROVIDER_LABEL[assignedAgent.cli_provider] ?? assignedAgent.cli_provider}
                                    </span>
                                  </div>
                                ) : (
                                  <span style={{ fontSize: "12px", color: missing ? "#fb7185" : "#9CA3AF" }}>
                                    {t({ ko: "에이전트를 선택하세요", en: "Select an agent", ja: "エージェントを選択", zh: "选择代理" })}
                                  </span>
                                )}
                              </div>
                              {/* Toggle dropdown */}
                              <button
                                type="button"
                                onClick={() => setOpenSlotIdx(isOpen ? null : idx)}
                                style={{
                                  ...mono, fontSize: "10px", padding: "4px 10px", flexShrink: 0,
                                  border: `1px solid ${isOpen ? "#3B82F6" : "#E5E7EB"}`,
                                  background: "transparent",
                                  color: isOpen ? "#3B82F6" : "#9CA3AF",
                                  cursor: "pointer",
                                  display: "flex", alignItems: "center", gap: 4,
                                }}
                              >
                                {slot.agentId ? t({ ko: "변경", en: "Change", ja: "変更", zh: "更改" }) : t({ ko: "선택", en: "Select", ja: "選択", zh: "选择" })}
                                <svg width="10" height="10" viewBox="0 0 10 10" fill="none" style={{ transform: isOpen ? "rotate(180deg)" : "none", transition: "transform 0.2s" }}>
                                  <path d="M2 3.5L5 6.5L8 3.5" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round"/>
                                </svg>
                              </button>
                              {/* Remove */}
                              {roleSlots.length > 1 && (
                                <button
                                  type="button"
                                  onClick={() => handleRemoveSlot(idx)}
                                  style={{
                                    flexShrink: 0, padding: "4px", cursor: "pointer",
                                    background: "none", border: "none",
                                    color: "#9CA3AF", opacity: 0.5,
                                  }}
                                >
                                  <svg width="12" height="12" viewBox="0 0 12 12" fill="none">
                                    <path d="M2.5 2.5L9.5 9.5M9.5 2.5L2.5 9.5" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round"/>
                                  </svg>
                                </button>
                              )}
                            </div>
                            {/* Dropdown */}
                            {isOpen && (
                              <div style={{ border: "1.5px solid #3B82F6", borderTop: "none", maxHeight: 200, overflowY: "auto", background: "#FFFFFF" }}>
                                {cliAgents.map(agent => {
                                  const isCurrent = agent.id === slot.agentId;
                                  return (
                                    <button
                                      key={agent.id}
                                      type="button"
                                      onClick={() => {
                                        setRoleSlots(prev => prev.map((s, i) => i === idx ? { ...s, agentId: agent.id } : s));
                                        setOpenSlotIdx(null);
                                      }}
                                      className="w-full flex items-center gap-3"
                                      style={{
                                        padding: "10px 14px",
                                        borderBottom: "1px solid #E5E7EB",
                                        background: isCurrent ? "rgba(245,158,11,0.08)" : "transparent",
                                        cursor: "pointer", textAlign: "left",
                                      }}
                                    >
                                      <svg width="16" height="16" viewBox="0 0 16 16" fill="none" style={{ flexShrink: 0, color: isCurrent ? "#3B82F6" : "#9CA3AF" }}>
                                        <rect x="3" y="5" width="10" height="8" rx="2" stroke="currentColor" strokeWidth="1.4"/>
                                        <circle cx="6" cy="9" r="1" fill="currentColor"/>
                                        <circle cx="10" cy="9" r="1" fill="currentColor"/>
                                        <path d="M6 4V3" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round"/>
                                        <path d="M10 4V3" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round"/>
                                      </svg>
                                      <div className="flex-1 min-w-0">
                                        <div className="flex items-center gap-2">
                                          <span style={{ ...display, fontSize: "13px", fontWeight: 600, color: isCurrent ? "#3B82F6" : "#111827" }}>
                                            {agent.name_ko || agent.name}
                                          </span>
                                          <span style={{ ...mono, fontSize: "10px", color: "#9CA3AF" }}>
                                            {PROVIDER_LABEL[agent.cli_provider] ?? agent.cli_provider}
                                          </span>
                                        </div>
                                        {agent.department && (
                                          <span style={{ ...mono, fontSize: "10px", color: "#9CA3AF", opacity: 0.6 }}>
                                            {agent.department.name_ko ?? agent.department.name}
                                          </span>
                                        )}
                                      </div>
                                      {isCurrent && (
                                        <svg width="14" height="14" viewBox="0 0 14 14" fill="none" style={{ flexShrink: 0, color: "#3B82F6" }}>
                                          <path d="M2.5 7L5.5 10L11.5 4" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"/>
                                        </svg>
                                      )}
                                    </button>
                                  );
                                })}
                              </div>
                            )}
                          </div>
                        );
                      })}

                      {/* Add role */}
                      <button
                        type="button"
                        onClick={handleAddSlot}
                        className="w-full flex items-center justify-center gap-2"
                        style={{
                          ...mono, fontSize: "11px", padding: "10px",
                          border: "1px dashed #E5E7EB",
                          background: "transparent",
                          color: "#9CA3AF",
                          cursor: "pointer",
                        }}
                      >
                        <svg width="12" height="12" viewBox="0 0 12 12" fill="none">
                          <path d="M6 2v8M2 6h8" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round"/>
                        </svg>
                        {t({ ko: "역할 추가", en: "Add role", ja: "役割追加", zh: "添加角色" })}
                      </button>
                    </div>
                  )}

                  {submitted && !canConfirmAgent && (
                    <p style={{ ...mono, fontSize: "11px", color: "#fb7185", padding: "8px 0" }}>
                      {t({ ko: "최소 1개 역할에 에이전트를 배정해주세요", en: "Assign at least one agent to a role", ja: "最低1つの役割にエージェントを配置してください", zh: "请至少为一个角色分配代理" })}
                    </p>
                  )}
                </div>
              );
            })()}
          </div>
        </div>

        {/* ── Footer: clean and focused ── */}
        <div
          className="flex items-center justify-between gap-2 px-5 py-3 flex-shrink-0"
          style={{ borderTop: "1px solid #E5E7EB", fontFamily: "var(--th-font-mono)" }}
        >
          {step === "github" ? (
            <button
              type="button"
              onClick={() => setStep("category")}
              style={{ ...mono, fontSize: "11px", color: "#9CA3AF", background: "none", border: "none", cursor: "pointer" }}
            >
              {t({ ko: "← 일반 생성", en: "← Normal create", ja: "← 通常作成", zh: "← 普通创建" })}
            </button>
          ) : (
            <Button variant="ghost" size="sm" onClick={goBack}>
              {t({ ko: "← 이전", en: "← Back", ja: "← 戻る", zh: "← 上一步" })}
            </Button>
          )}

          {step !== "github" && (
            step === "agent" ? (
              <Button variant="primary" size="sm" onClick={handleConfirm} disabled={busy || !canConfirmAgent}>
                {busy
                  ? t({ ko: "생성 중...", en: "Creating...", ja: "作成中...", zh: "创建中..." })
                  : t({ ko: "프로젝트 시작", en: "Start Project", ja: "プロジェクト開始", zh: "开始项目" })}
              </Button>
            ) : step === "category" ? (
              <Button variant="primary" size="sm" onClick={() => setStep("directive")} disabled={!selectedCategoryId}>
                {t({ ko: "다음", en: "Next", ja: "次へ", zh: "下一步" })}
              </Button>
            ) : step === "directive" ? (
              <Button variant="primary" size="sm" onClick={() => setStep("info")}>
                {t({ ko: "다음", en: "Next", ja: "次へ", zh: "下一步" })}
              </Button>
            ) : (
              <Button variant="primary" size="sm" onClick={() => setStep("agent")} disabled={!canConfirmInfo}>
                {t({ ko: "다음", en: "Next", ja: "次へ", zh: "下一步" })}
              </Button>
            )
          )}
        </div>
      </AppWindow>

      <ManualPathPickerDialog
        open={pathTools.manualPathPickerOpen}
        t={t}
        manualPathCurrent={pathTools.manualPathCurrent}
        manualPathParent={pathTools.manualPathParent}
        manualPathEntries={pathTools.manualPathEntries}
        manualPathLoading={pathTools.manualPathLoading}
        manualPathError={pathTools.manualPathError}
        manualPathTruncated={pathTools.manualPathTruncated}
        onClose={() => pathTools.setManualPathPickerOpen(false)}
        onLoadEntries={pathTools.loadManualPathEntries}
        onSelectCurrent={handlePathSelected}
      />
    </>
  );
}
