import { useCallback, useEffect, useRef, useState } from "react";
import type { Category } from "../../types";
import { Modal, ModalHeader, ModalBody, ModalFooter, Button, Input, FormField } from "../ui";
import ManualPathPickerDialog from "../project-manager/ManualPathPickerDialog";
import { useProjectManagerPathTools } from "../project-manager/useProjectManagerPathTools";
import CategorySelectStep from "./CategorySelectStep";
import { useI18n } from "../../i18n";

interface ProjectCreateModalProps {
  categories: Category[];
  onConfirm: (params: { name: string; categoryId: string | null; project_path: string; core_goal?: string }) => void;
  onClose: () => void;
}

type Step = "category" | "info";

function parseSchema(schema: string): string[] {
  try {
    const parsed = JSON.parse(schema);
    if (Array.isArray(parsed)) {
      return parsed
        .slice(0, 3)
        .map((item: Record<string, string>) => item.name ?? item.title ?? item.label ?? "")
        .filter(Boolean);
    }
  } catch { /* ignore */ }
  return [];
}

export default function ProjectCreateModal({ categories, onConfirm, onClose }: ProjectCreateModalProps) {
  const [step, setStep] = useState<Step>("category");
  const [selectedCategoryId, setSelectedCategoryId] = useState<string | null>(null);
  const [projectName, setProjectName] = useState("");
  const [projectPath, setProjectPath] = useState("");
  const [coreGoal, setCoreGoal] = useState("");
  const [submitted, setSubmitted] = useState(false);
  const [busy, setBusy] = useState(false);
  const [pathAutoGenerated, setPathAutoGenerated] = useState(true);
  const autoAdvanceTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

  const { t, language } = useI18n();

  const pathTools = useProjectManagerPathTools({
    t,
    projectPath,
    pathToolsVisible: step === "info",
  });

  // Auto-generate project_path from name (only while auto-generated is active)
  useEffect(() => {
    if (!pathAutoGenerated) return;
    if (!projectName.trim()) {
      setProjectPath("");
      return;
    }
    const safeName = projectName
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9가-힣]+/g, "-")
      .replace(/^-|-$/g, "");
    setProjectPath(`~/projects/${safeName}`);
  }, [projectName, pathAutoGenerated]);

  const handlePathChange = (value: string) => {
    setPathAutoGenerated(false);
    setProjectPath(value);
  };

  const handleCategorySelect = (id: string) => {
    setSelectedCategoryId(id);
    if (autoAdvanceTimer.current) clearTimeout(autoAdvanceTimer.current);
    autoAdvanceTimer.current = setTimeout(() => setStep("info"), 300);
  };

  const handleOpenBrowser = useCallback(async () => {
    pathTools.setManualPathPickerOpen(true);
    await pathTools.loadManualPathEntries(undefined);
  }, [pathTools]);

  const handlePathSelected = useCallback(() => {
    if (pathTools.manualPathCurrent) {
      setProjectPath(pathTools.manualPathCurrent);
      setPathAutoGenerated(false);
    }
    pathTools.setManualPathPickerOpen(false);
  }, [pathTools]);

  const selectedCategory = categories.find((c) => c.id === selectedCategoryId) ?? null;
  const canConfirm = projectName.trim().length > 0 && projectPath.trim().length > 0;

  const handleConfirm = () => {
    setSubmitted(true);
    if (!canConfirm) return;
    setBusy(true);
    onConfirm({
      name: projectName.trim(),
      categoryId: selectedCategoryId,
      project_path: projectPath.trim(),
      core_goal: coreGoal.trim() || (selectedCategory ? `${selectedCategory.name_ko ?? selectedCategory.name} 프로젝트` : undefined),
    });
  };

  /* Category display name based on language */
  const categoryDisplayName = (cat: Category) => {
    if (language === "ko") return cat.name_ko ?? cat.name;
    return cat.name;
  };

  /* Auto-include summary */
  const autoIncludeItems: { icon: string; label: string }[] = [];
  if (selectedCategory) {
    const gates = parseSchema(selectedCategory.gate_schema);
    const deliverables = parseSchema(selectedCategory.deliverable_schema);
    const kpis = parseSchema(selectedCategory.kpi_schema);
    if (gates.length > 0) {
      autoIncludeItems.push({
        icon: "✓",
        label: t({
          ko: `검토 단계 ${gates.length}개 (${gates.join(", ")})`,
          en: `${gates.length} review gate(s) (${gates.join(", ")})`,
          ja: `レビューゲート ${gates.length}件 (${gates.join(", ")})`,
          zh: `${gates.length} 个审查阶段 (${gates.join(", ")})`,
        }),
      });
    }
    if (deliverables.length > 0) {
      autoIncludeItems.push({
        icon: "✓",
        label: t({
          ko: `결과물 목록 (${deliverables.join(", ")})`,
          en: `Deliverables (${deliverables.join(", ")})`,
          ja: `成果物 (${deliverables.join(", ")})`,
          zh: `交付物 (${deliverables.join(", ")})`,
        }),
      });
    }
    if (kpis.length > 0) {
      autoIncludeItems.push({
        icon: "✓",
        label: t({
          ko: `성과 지표 ${kpis.length}개`,
          en: `${kpis.length} KPI(s)`,
          ja: `KPI ${kpis.length}件`,
          zh: `${kpis.length} 个 KPI`,
        }),
      });
    }
    if (autoIncludeItems.length === 0) {
      autoIncludeItems.push({
        icon: "✓",
        label: t({
          ko: "유형에 맞는 목표·검토 단계·결과물 양식",
          en: "Goal, review gates & deliverable templates for this type",
          ja: "このタイプに合わせた目標・レビュー・成果物テンプレート",
          zh: "适合此类型的目标、审查阶段和交付物模板",
        }),
      });
    }
    autoIncludeItems.push({
      icon: "ℹ",
      label: t({
        ko: "나중에 원하는 대로 수정할 수 있어요.",
        en: "You can edit these anytime.",
        ja: "後からいつでも編集できます。",
        zh: "您可以随时修改这些设置。",
      }),
    });
  }

  return (
    <>
      <Modal open onClose={onClose} width="md">
        <ModalHeader onClose={onClose}>
          {t({ ko: "새 프로젝트", en: "New Project", ja: "新規プロジェクト", zh: "新建项目" })}
        </ModalHeader>

        {/* Step indicator */}
        <div className="flex items-center gap-2 px-5 pt-4 pb-1 text-[11px]">
          <span
            className={step === "category" ? "font-semibold" : ""}
            style={{ color: step === "category" ? "var(--th-accent)" : "var(--th-text-muted)" }}
          >
            {t({ ko: "① 유형 선택", en: "① Select type", ja: "① タイプ選択", zh: "① 选择类型" })}
          </span>
          <span style={{ color: "var(--th-border)" }}>────</span>
          <span
            className={step === "info" ? "font-semibold" : ""}
            style={{ color: step === "info" ? "var(--th-accent)" : "var(--th-text-muted)" }}
          >
            {t({ ko: "② 기본 정보", en: "② Basic info", ja: "② 基本情報", zh: "② 基本信息" })}
          </span>
        </div>

        <ModalBody>
          {step === "category" ? (
            <>
              <p className="text-xs mb-1" style={{ color: "var(--th-text-muted)" }}>
                {t({ ko: "어떤 종류의 프로젝트인가요?", en: "What kind of project is this?", ja: "どの種類のプロジェクトですか？", zh: "这是什么类型的项目？" })}
              </p>
              <p className="text-[11px] mb-3" style={{ color: "var(--th-text-muted)" }}>
                {t({
                  ko: "유형에 맞는 목표·체크포인트·결과물 양식이 자동 설정됩니다.",
                  en: "Goals, checkpoints & deliverable templates will be auto-configured for this type.",
                  ja: "このタイプに合わせた目標・チェックポイント・成果物テンプレートが自動設定されます。",
                  zh: "系统将根据类型自动配置目标、检查点和交付物模板。",
                })}
              </p>
              <CategorySelectStep
                categories={categories}
                selectedId={selectedCategoryId}
                onSelect={handleCategorySelect}
              />
            </>
          ) : (
            <div className="space-y-4">
              {/* Selected category badge */}
              {selectedCategory ? (
                <div
                  className="flex items-center gap-2 px-3 py-2 text-xs"
                  style={{
                    borderRadius: "2px",
                    border: `1px solid ${selectedCategory.color}44`,
                    background: `${selectedCategory.color}11`,
                  }}
                >
                  <span className="font-semibold" style={{ color: selectedCategory.color }}>
                    {t({ ko: "선택한 유형:", en: "Type:", ja: "タイプ:", zh: "类型：" })}{" "}
                    {categoryDisplayName(selectedCategory)}
                  </span>
                  <button
                    onClick={() => setStep("category")}
                    className="ml-auto text-[10px] underline transition-colors"
                    style={{ color: "var(--th-text-muted)" }}
                  >
                    {t({ ko: "변경", en: "Change", ja: "変更", zh: "更改" })}
                  </button>
                </div>
              ) : (
                <div
                  className="flex items-center gap-2 px-3 py-2 text-xs"
                  style={{ borderRadius: "2px", border: "1px solid var(--th-border)", color: "var(--th-text-muted)" }}
                >
                  {t({ ko: "유형 없이 시작", en: "No type selected", ja: "タイプなしで開始", zh: "无类型开始" })}
                  <button
                    onClick={() => setStep("category")}
                    className="ml-auto text-[10px] underline transition-colors"
                    style={{ color: "var(--th-text-muted)" }}
                  >
                    {t({ ko: "변경", en: "Change", ja: "変更", zh: "更改" })}
                  </button>
                </div>
              )}

              <FormField
                label={t({ ko: "프로젝트 이름", en: "Project name", ja: "プロジェクト名", zh: "项目名称" })}
                required
                error={submitted && !projectName.trim()
                  ? t({ ko: "프로젝트 이름을 입력해주세요.", en: "Please enter a project name.", ja: "プロジェクト名を入力してください。", zh: "请输入项目名称。" })
                  : undefined}
              >
                <Input
                  autoFocus
                  value={projectName}
                  onChange={(e) => setProjectName(e.target.value)}
                  placeholder={t({ ko: "예: 쇼핑몰 앱 개발 2026", en: "e.g. Shopping App 2026", ja: "例: ショッピングアプリ 2026", zh: "例如：电商应用 2026" })}
                  error={submitted && !projectName.trim()}
                />
              </FormField>

              {/* Project path with folder browser */}
              <FormField
                label={t({ ko: "프로젝트 경로", en: "Project path", ja: "プロジェクトパス", zh: "项目路径" })}
                required
                hint={t({ ko: "AI 에이전트가 실행될 로컬 폴더 경로입니다.", en: "Local folder path where the AI agent will run.", ja: "AIエージェントが実行されるローカルフォルダのパスです。", zh: "AI 代理将在此本地文件夹路径中运行。" })}
                error={submitted && !projectPath.trim()
                  ? t({ ko: "프로젝트 경로는 필수입니다.", en: "Project path is required.", ja: "プロジェクトパスは必須です。", zh: "项目路径为必填项。" })
                  : undefined}
              >
                <div className="flex items-stretch gap-2">
                  <div className="flex-1">
                    <Input
                      value={projectPath}
                      onChange={(e) => handlePathChange(e.target.value)}
                      placeholder="/Users/me/projects/my-app"
                      mono
                      error={submitted && !projectPath.trim()}
                    />
                  </div>
                  {/* Browse button */}
                  {!pathTools.pathApiUnsupported && (
                    <button
                      type="button"
                      onClick={() => void handleOpenBrowser()}
                      title={t({ ko: "폴더 탐색", en: "Browse folders", ja: "フォルダを参照", zh: "浏览文件夹" })}
                      style={{
                        padding: "0 10px",
                        borderRadius: "2px",
                        border: "1px solid var(--th-border)",
                        background: "var(--th-bg-surface)",
                        color: "var(--th-text-secondary)",
                        fontFamily: "var(--th-font-mono)",
                        fontSize: "0.7rem",
                        cursor: "pointer",
                        whiteSpace: "nowrap",
                        flexShrink: 0,
                      }}
                    >
                      📁 {t({ ko: "탐색", en: "Browse", ja: "参照", zh: "浏览" })}
                    </button>
                  )}
                </div>

                {/* Auto-generated path hint */}
                {pathAutoGenerated && projectPath && (
                  <p
                    className="mt-1 text-[10px] font-mono"
                    style={{ color: "var(--th-text-muted)" }}
                  >
                    {t({ ko: "자동 생성됨 · 직접 입력하거나 탐색으로 변경하세요", en: "Auto-generated · edit or browse to change", ja: "自動生成済み · 編集または参照で変更できます", zh: "自动生成 · 可直接编辑或通过浏览更改" })}
                  </p>
                )}

                {/* Path API unsupported hint */}
                {pathTools.pathApiUnsupported && (
                  <p
                    className="mt-1 text-[10px] font-mono"
                    style={{ color: "var(--th-text-muted)" }}
                  >
                    {pathTools.unsupportedPathApiMessage}
                  </p>
                )}

                {/* Form feedback (e.g. browse errors) */}
                {pathTools.formFeedback && (
                  <p
                    className="mt-1 text-[10px] font-mono"
                    style={{
                      color: pathTools.formFeedback.tone === "error"
                        ? "var(--th-danger-text)"
                        : "var(--th-text-muted)",
                    }}
                  >
                    {pathTools.formFeedback.message}
                  </p>
                )}
              </FormField>

              <FormField
                label={t({ ko: "한 줄 목표", en: "One-line goal", ja: "一言ゴール", zh: "一句话目标" })}
                suffix={t({ ko: "(선택)", en: "(optional)", ja: "(任意)", zh: "（可选）" })}
              >
                <Input
                  value={coreGoal}
                  onChange={(e) => setCoreGoal(e.target.value)}
                  onKeyDown={(e) => e.key === "Enter" && !busy && handleConfirm()}
                  placeholder={t({ ko: "예: 2026년 Q2 출시를 위한 신규 기능 개발", en: "e.g. New feature development for Q2 2026 launch", ja: "例: 2026年Q2リリースに向けた新機能開発", zh: "例如：2026 年 Q2 发布的新功能开发" })}
                />
              </FormField>

              {/* Auto-include summary */}
              {selectedCategory && autoIncludeItems.length > 0 && (
                <div
                  className="px-3 py-2.5 text-xs space-y-1"
                  style={{
                    borderRadius: "2px",
                    background: "var(--th-amber-glow)",
                    border: "1px solid var(--th-border-accent)",
                  }}
                >
                  <p className="font-medium text-[11px] mb-1.5" style={{ color: "var(--th-text-muted)" }}>
                    {t({ ko: "이 유형에는 다음이 자동 포함됩니다", en: "This type auto-includes", ja: "このタイプには以下が自動含まれます", zh: "此类型自动包含以下内容" })}
                  </p>
                  {autoIncludeItems.map((item, i) => (
                    <div key={i} className="flex items-start gap-1.5" style={{ color: "var(--th-text-muted)" }}>
                      <span className="flex-shrink-0">{item.icon}</span>
                      <span>{item.label}</span>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}
        </ModalBody>

        <ModalFooter className="justify-between">
          {step === "info" ? (
            <Button variant="ghost" size="sm" onClick={() => setStep("category")}>
              {t({ ko: "← 이전", en: "← Back", ja: "← 戻る", zh: "← 上一步" })}
            </Button>
          ) : (
            <Button
              variant="ghost"
              size="sm"
              onClick={() => { setSelectedCategoryId(null); setStep("info"); }}
            >
              {t({ ko: "유형 없이 시작하기", en: "Start without type", ja: "タイプなしで開始", zh: "不选类型继续" })}
            </Button>
          )}

          {step === "category" ? (
            <div className="flex items-center gap-3">
              {!selectedCategoryId && (
                <span className="text-[10px]" style={{ color: "var(--th-text-muted)" }}>
                  {t({ ko: "유형을 선택해야 다음으로 갈 수 있어요", en: "Select a type to continue", ja: "タイプを選択してから次に進めます", zh: "请先选择类型再继续" })}
                </span>
              )}
              <Button
                variant="primary"
                size="sm"
                onClick={() => setStep("info")}
                disabled={!selectedCategoryId}
              >
                {t({ ko: "다음 →", en: "Next →", ja: "次へ →", zh: "下一步 →" })}
              </Button>
            </div>
          ) : (
            <Button
              variant="primary"
              size="sm"
              onClick={handleConfirm}
              disabled={busy || !canConfirm}
            >
              {busy
                ? t({ ko: "생성 중…", en: "Creating…", ja: "作成中…", zh: "创建中…" })
                : t({ ko: "시작!", en: "Create!", ja: "作成!", zh: "创建!" })}
            </Button>
          )}
        </ModalFooter>
      </Modal>

      {/* Folder browser dialog — rendered outside Modal to avoid z-index conflicts */}
      <ManualPathPickerDialog
        open={pathTools.manualPathPickerOpen}
        t={t}
        manualPathCurrent={pathTools.manualPathCurrent}
        manualPathParent={pathTools.manualPathParent}
        manualPathEntries={pathTools.manualPathEntries}
        manualPathLoading={pathTools.manualPathLoading}
        manualPathError={pathTools.manualPathError}
        manualPathTruncated={pathTools.manualPathTruncated}
        onClose={() => pathTools.setManualPathPickerOpen(false)}
        onLoadEntries={pathTools.loadManualPathEntries}
        onSelectCurrent={handlePathSelected}
      />
    </>
  );
}
