import type { Localized } from "./types";

/** First part of DEPARTMENT_PERSON_NAME_POOL (planning through report:devsecops). */
export const NAME_POOL_A: Partial<Record<string, Localized[]>> = {
  planning: [
    { ko: "세이지", en: "Sage", ja: "セージ", zh: "赛吉" },
    { ko: "미나", en: "Mina", ja: "ミナ", zh: "米娜" },
    { ko: "주노", en: "Juno", ja: "ジュノ", zh: "朱诺" },
    { ko: "리안", en: "Rian", ja: "リアン", zh: "里安" },
    { ko: "하루", en: "Haru", ja: "ハル", zh: "晴" },
    { ko: "노아", en: "Noa", ja: "ノア", zh: "诺亚" },
  ],
  dev: [
    { ko: "아리아", en: "Aria", ja: "アリア", zh: "阿莉娅" },
    { ko: "테오", en: "Theo", ja: "テオ", zh: "西奥" },
    { ko: "카이", en: "Kai", ja: "カイ", zh: "凯" },
    { ko: "리암", en: "Liam", ja: "リアム", zh: "利亚姆" },
    { ko: "세나", en: "Sena", ja: "セナ", zh: "塞娜" },
    { ko: "로완", en: "Rowan", ja: "ローワン", zh: "罗恩" },
  ],
  design: [
    { ko: "도로", en: "Doro", ja: "ドロ", zh: "多罗" },
    { ko: "루나", en: "Luna", ja: "ルナ", zh: "露娜" },
    { ko: "픽셀", en: "Pixel", ja: "ピクセル", zh: "像素" },
    { ko: "유나", en: "Yuna", ja: "ユナ", zh: "优娜" },
    { ko: "미로", en: "Miro", ja: "ミロ", zh: "米洛" },
    { ko: "아이리스", en: "Iris", ja: "アイリス", zh: "爱丽丝" },
  ],
  qa: [
    { ko: "스피키", en: "Speaky", ja: "スピーキー", zh: "斯皮奇" },
    { ko: "호크", en: "Hawk", ja: "ホーク", zh: "霍克" },
    { ko: "베라", en: "Vera", ja: "ヴェラ", zh: "薇拉" },
    { ko: "퀸", en: "Quinn", ja: "クイン", zh: "奎因" },
    { ko: "토리", en: "Tori", ja: "トリ", zh: "托莉" },
    { ko: "하윤", en: "Hayoon", ja: "ハユン", zh: "夏允" },
  ],
  operations: [
    { ko: "아틀라스", en: "Atlas", ja: "アトラス", zh: "阿特拉斯" },
    { ko: "나리", en: "Nari", ja: "ナリ", zh: "娜莉" },
    { ko: "오웬", en: "Owen", ja: "オーウェン", zh: "欧文" },
    { ko: "다미", en: "Dami", ja: "ダミ", zh: "达米" },
    { ko: "키라", en: "Kira", ja: "キラ", zh: "琪拉" },
    { ko: "솔", en: "Sol", ja: "ソル", zh: "索尔" },
  ],
  devsecops: [
    { ko: "볼트S", en: "VoltS", ja: "ボルトS", zh: "伏特S" },
    { ko: "시온", en: "Sion", ja: "シオン", zh: "锡安" },
    { ko: "녹스", en: "Knox", ja: "ノックス", zh: "诺克斯" },
    { ko: "레이븐", en: "Raven", ja: "レイヴン", zh: "渡鸦" },
    { ko: "미라", en: "Mira", ja: "ミラ", zh: "米拉" },
    { ko: "알렉스", en: "Alex", ja: "アレックス", zh: "亚历克斯" },
  ],
  "asset_management:planning": [
    { ko: "워런 버핏", en: "Warren Buffett", ja: "ウォーレン・バフェット", zh: "沃伦·巴菲特" },
    { ko: "조지 소로스", en: "George Soros", ja: "ジョージ・ソロス", zh: "乔治·索罗斯" },
    { ko: "레이 달리오", en: "Ray Dalio", ja: "レイ・ダリオ", zh: "瑞·达利欧" },
    { ko: "피터 린치", en: "Peter Lynch", ja: "ピーター・リンチ", zh: "彼得·林奇" },
    { ko: "벤저민 그레이엄", en: "Benjamin Graham", ja: "ベンジャミン・グレアム", zh: "本杰明·格雷厄姆" },
    { ko: "찰리 멍거", en: "Charlie Munger", ja: "チャーリー・マンガー", zh: "查理·芒格" },
  ],
  "asset_management:dev": [
    { ko: "짐 사이먼스", en: "Jim Simons", ja: "ジム・サイモンズ", zh: "詹姆斯·西蒙斯" },
    { ko: "에드 소프", en: "Ed Thorp", ja: "エド・ソープ", zh: "爱德华·索普" },
    { ko: "피셔 블랙", en: "Fischer Black", ja: "フィッシャー・ブラック", zh: "费希尔·布莱克" },
    { ko: "마이런 숄스", en: "Myron Scholes", ja: "マイロン・ショールズ", zh: "迈伦·斯科尔斯" },
    { ko: "이매뉴얼 더먼", en: "Emanuel Derman", ja: "エマニュエル・ダーマン", zh: "伊曼纽尔·德曼" },
    { ko: "데이비드 쇼", en: "David Shaw", ja: "デビッド・ショー", zh: "大卫·肖" },
  ],
  "asset_management:design": [
    { ko: "필립 피셔", en: "Philip Fisher", ja: "フィリップ・フィッシャー", zh: "菲利普·费雪" },
    { ko: "존 템플턴", en: "John Templeton", ja: "ジョン・テンプルトン", zh: "约翰·邓普顿" },
    { ko: "하워드 막스", en: "Howard Marks", ja: "ハワード・マークス", zh: "霍华德·马克斯" },
    { ko: "캐시 우드", en: "Cathie Wood", ja: "キャシー・ウッド", zh: "凯西·伍德" },
    { ko: "메리 미커", en: "Mary Meeker", ja: "メアリー・ミーカー", zh: "玛丽·米克尔" },
    { ko: "애비 코언", en: "Abby Cohen", ja: "アビー・コーエン", zh: "阿比·科恩" },
  ],
  "asset_management:qa": [
    { ko: "나심 탈레브", en: "Nassim Taleb", ja: "ナシーム・タレブ", zh: "纳西姆·塔勒布" },
    { ko: "해리 마코위츠", en: "Harry Markowitz", ja: "ハリー・マーコウィッツ", zh: "哈里·马科维茨" },
    { ko: "로버트 머튼", en: "Robert Merton", ja: "ロバート・マートン", zh: "罗伯特·默顿" },
    { ko: "다니엘 카너먼", en: "Daniel Kahneman", ja: "ダニエル・カーネマン", zh: "丹尼尔·卡尼曼" },
    { ko: "프랭크 나이트", en: "Frank Knight", ja: "フランク・ナイト", zh: "弗兰克·奈特" },
    { ko: "존 헐", en: "John Hull", ja: "ジョン・ハル", zh: "约翰·赫尔" },
  ],
  "asset_management:devsecops": [
    { ko: "폴 볼커", en: "Paul Volcker", ja: "ポール・ボルカー", zh: "保罗·沃尔克" },
    { ko: "재닛 옐런", en: "Janet Yellen", ja: "ジャネット・イエレン", zh: "珍妮特·耶伦" },
    { ko: "벤 버냉키", en: "Ben Bernanke", ja: "ベン・バーナンキ", zh: "本·伯南克" },
    { ko: "브룩슬리 본", en: "Brooksley Born", ja: "ブルックスリー・ボーン", zh: "布鲁克斯利·博恩" },
    { ko: "게리 겐슬러", en: "Gary Gensler", ja: "ゲイリー・ゲンスラー", zh: "加里·根斯勒" },
    { ko: "아서 레빗", en: "Arthur Levitt", ja: "アーサー・レビット", zh: "阿瑟·莱维特" },
  ],
  "asset_management:operations": [
    { ko: "존 보글", en: "John Bogle", ja: "ジョン・ボーグル", zh: "约翰·博格" },
    { ko: "래리 핑크", en: "Larry Fink", ja: "ラリー・フィンク", zh: "拉里·芬克" },
    { ko: "데이비드 스웬슨", en: "David Swensen", ja: "デビッド・スウェンセン", zh: "大卫·斯文森" },
    { ko: "애비게일 존슨", en: "Abigail Johnson", ja: "アビゲイル・ジョンソン", zh: "阿比盖尔·约翰逊" },
    { ko: "켄 그리핀", en: "Kenneth Griffin", ja: "ケネス・グリフィン", zh: "肯尼斯·格里芬" },
    { ko: "칼 아이칸", en: "Carl Icahn", ja: "カール・アイカーン", zh: "卡尔·伊坎" },
  ],
  "report:planning": [
    { ko: "조셉 퓰리처", en: "Joseph Pulitzer", ja: "ジョセフ・ピューリツァー", zh: "约瑟夫·普利策" },
    { ko: "캐서린 그레이엄", en: "Katharine Graham", ja: "キャサリン・グラハム", zh: "凯瑟琳·格雷厄姆" },
    { ko: "밥 우드워드", en: "Bob Woodward", ja: "ボブ・ウッドワード", zh: "鲍勃·伍德沃德" },
    { ko: "월터 리프먼", en: "Walter Lippmann", ja: "ウォルター・リップマン", zh: "沃尔特·李普曼" },
    { ko: "칼 번스타인", en: "Carl Bernstein", ja: "カール・バーンスタイン", zh: "卡尔·伯恩斯坦" },
    { ko: "호레이스 그릴리", en: "Horace Greeley", ja: "ホレス・グリーリー", zh: "霍勒斯·格里利" },
  ],
  "report:dev": [
    { ko: "한스 로슬링", en: "Hans Rosling", ja: "ハンス・ロスリング", zh: "汉斯·罗斯林" },
    { ko: "플로렌스 나이팅게일", en: "Florence Nightingale", ja: "フローレンス・ナイチンゲール", zh: "弗洛伦斯·南丁格尔" },
    { ko: "네이트 실버", en: "Nate Silver", ja: "ネイト・シルバー", zh: "内特·西尔弗" },
    { ko: "에드워드 터프티", en: "Edward Tufte", ja: "エドワード・タフティ", zh: "爱德华·塔夫特" },
    { ko: "존 스노우", en: "John Snow", ja: "ジョン・スノウ", zh: "约翰·斯诺" },
    { ko: "W.E.B. 두보이스", en: "W.E.B. Du Bois", ja: "W.E.B.デュボイス", zh: "W.E.B.杜波依斯" },
  ],
  "report:design": [
    { ko: "마시모 비넬리", en: "Massimo Vignelli", ja: "マッシモ・ヴィニェッリ", zh: "马西莫·维涅利" },
    { ko: "얀 치홀트", en: "Jan Tschichold", ja: "ヤン・チヒョルト", zh: "扬·奇肖尔德" },
    { ko: "폴 랜드", en: "Paul Rand", ja: "ポール・ランド", zh: "保罗·兰德" },
    { ko: "요제프 뮐러브로크만", en: "Josef Mueller-Brockmann", ja: "ヨゼフ・ミューラーブロックマン", zh: "约瑟夫·米勒-布罗克曼" },
    { ko: "베아트리스 워드", en: "Beatrice Warde", ja: "ベアトリス・ウォード", zh: "比阿特丽斯·沃德" },
    { ko: "에릭 슈피커만", en: "Erik Spiekermann", ja: "エリック・シュピーカーマン", zh: "埃里克·施皮克曼" },
  ],
  "report:qa": [
    { ko: "윌리엄 스트렁크", en: "William Strunk", ja: "ウィリアム・ストランク", zh: "威廉·斯特伦克" },
    { ko: "E.B. 화이트", en: "E.B. White", ja: "E.B.ホワイト", zh: "E.B.怀特" },
    { ko: "윌리엄 사파이어", en: "William Safire", ja: "ウィリアム・サファイア", zh: "威廉·萨菲尔" },
    { ko: "린 트러스", en: "Lynne Truss", ja: "リン・トラス", zh: "琳恩·特拉斯" },
    { ko: "메리 노리스", en: "Mary Norris", ja: "メアリー・ノリス", zh: "玛丽·诺里斯" },
    { ko: "벤저민 드레이어", en: "Benjamin Dreyer", ja: "ベンジャミン・ドレイヤー", zh: "本杰明·德莱尔" },
  ],
  "report:operations": [
    { ko: "테드 터너", en: "Ted Turner", ja: "テッド・ターナー", zh: "特德·特纳" },
    { ko: "루퍼트 머독", en: "Rupert Murdoch", ja: "ルパート・マードック", zh: "鲁伯特·默多克" },
    { ko: "아리아나 허핑턴", en: "Arianna Huffington", ja: "アリアナ・ハフィントン", zh: "阿里安娜·赫芬顿" },
    { ko: "윌리엄 허스트", en: "William Hearst", ja: "ウィリアム・ハースト", zh: "威廉·赫斯特" },
    { ko: "오프라 윈프리", en: "Oprah Winfrey", ja: "オプラ・ウィンフリー", zh: "奥普拉·温弗瑞" },
    { ko: "헨리 루스", en: "Henry Luce", ja: "ヘンリー・ルース", zh: "亨利·卢斯" },
  ],
  "report:devsecops": [
    { ko: "에드워드 머로", en: "Edward R. Murrow", ja: "エドワード・マロー", zh: "爱德华·默罗" },
    { ko: "월터 크롱카이트", en: "Walter Cronkite", ja: "ウォルター・クロンカイト", zh: "沃尔特·克朗凯特" },
    { ko: "아이다 B. 웰스", en: "Ida B. Wells", ja: "アイダ・B・ウェルズ", zh: "艾达·B·威尔斯" },
    { ko: "넬리 블라이", en: "Nellie Bly", ja: "ネリー・ブライ", zh: "奈莉·布莱" },
    { ko: "대니얼 엘스버그", en: "Daniel Ellsberg", ja: "ダニエル・エルズバーグ", zh: "丹尼尔·埃尔斯伯格" },
    { ko: "I.F. 스톤", en: "I.F. Stone", ja: "I.F.ストーン", zh: "I.F.斯通" },
  ],
};
