import type { Localized } from "./types";

/** Second part of DEPARTMENT_PERSON_NAME_POOL (web_research_report through roleplay). */
export const NAME_POOL_B: Partial<Record<string, Localized[]>> = {
  "web_research_report:planning": [
    { ko: "팀 버너스리", en: "Tim Berners-Lee", ja: "ティム・バーナーズリー", zh: "蒂姆·伯纳斯-李" },
    { ko: "바네바 부시", en: "Vannevar Bush", ja: "ヴァネヴァー・ブッシュ", zh: "万尼瓦尔·布什" },
    { ko: "래리 페이지", en: "Larry Page", ja: "ラリー・ペイジ", zh: "拉里·佩奇" },
    { ko: "세르게이 브린", en: "Sergey Brin", ja: "セルゲイ・ブリン", zh: "谢尔盖·布林" },
    { ko: "지미 웨일스", en: "Jimmy Wales", ja: "ジミー・ウェールズ", zh: "吉米·威尔士" },
    { ko: "브루스터 케일", en: "Brewster Kahle", ja: "ブリュースター・ケール", zh: "布鲁斯特·卡利" },
  ],
  "web_research_report:dev": [
    { ko: "클로드 섀넌", en: "Claude Shannon", ja: "クロード・シャノン", zh: "克劳德·香农" },
    { ko: "빈트 서프", en: "Vint Cerf", ja: "ヴィント・サーフ", zh: "温顿·瑟夫" },
    { ko: "테드 넬슨", en: "Ted Nelson", ja: "テッド・ネルソン", zh: "泰德·尼尔森" },
    { ko: "더그 엥겔바트", en: "Doug Engelbart", ja: "ダグ・エンゲルバート", zh: "道格·恩格尔巴特" },
    { ko: "레이 톰린슨", en: "Ray Tomlinson", ja: "レイ・トムリンソン", zh: "雷·汤姆林森" },
    { ko: "앨런 케이", en: "Alan Kay", ja: "アラン・ケイ", zh: "艾伦·凯" },
  ],
  "web_research_report:design": [
    { ko: "데이비드 맥캔들리스", en: "David McCandless", ja: "デビッド・マキャンドレス", zh: "大卫·麦坎德利斯" },
    { ko: "니콜라스 펠턴", en: "Nicholas Felton", ja: "ニコラス・フェルトン", zh: "尼古拉斯·费尔顿" },
    { ko: "조르지아 루피", en: "Giorgia Lupi", ja: "ジョルジア・ルピ", zh: "乔治亚·卢皮" },
    { ko: "알베르토 카이로", en: "Alberto Cairo", ja: "アルベルト・カイロ", zh: "阿尔贝托·开罗" },
    { ko: "아만다 콕스", en: "Amanda Cox", ja: "アマンダ・コックス", zh: "阿曼达·考克斯" },
    { ko: "페르난다 비에가스", en: "Fernanda Viegas", ja: "フェルナンダ・ヴィエガス", zh: "费尔南达·维加斯" },
  ],
  "web_research_report:qa": [
    { ko: "아이다 타벨", en: "Ida Tarbell", ja: "アイダ・ターベル", zh: "艾达·塔贝尔" },
    { ko: "시모어 허시", en: "Seymour Hersh", ja: "シーモア・ハーシュ", zh: "西摩·赫什" },
    { ko: "크리스티안 아만푸르", en: "Christiane Amanpour", ja: "クリスティアン・アマンプール", zh: "克里斯蒂安·阿曼普尔" },
    { ko: "글렌 그린월드", en: "Glenn Greenwald", ja: "グレン・グリーンウォルド", zh: "格伦·格林沃尔德" },
    { ko: "안나 폴리트콥스카야", en: "Anna Politkovskaya", ja: "アンナ・ポリトコフスカヤ", zh: "安娜·波利特科夫斯卡娅" },
    { ko: "칼 세이건", en: "Carl Sagan", ja: "カール・セーガン", zh: "卡尔·萨根" },
  ],
  "web_research_report:operations": [
    { ko: "마크 앤드리슨", en: "Marc Andreessen", ja: "マーク・アンドリーセン", zh: "马克·安德森" },
    { ko: "제프 베이조스", en: "Jeff Bezos", ja: "ジェフ・ベゾス", zh: "杰夫·贝索斯" },
    { ko: "에브 윌리엄스", en: "Ev Williams", ja: "エヴ・ウィリアムズ", zh: "埃夫·威廉斯" },
    { ko: "잭 도시", en: "Jack Dorsey", ja: "ジャック・ドーシー", zh: "杰克·多西" },
    { ko: "리드 호프만", en: "Reid Hoffman", ja: "リード・ホフマン", zh: "里德·霍夫曼" },
    { ko: "마리사 메이어", en: "Marissa Mayer", ja: "マリッサ・メイヤー", zh: "玛丽莎·梅耶尔" },
  ],
  "web_research_report:devsecops": [
    { ko: "브루스 슈나이어", en: "Bruce Schneier", ja: "ブルース・シュナイアー", zh: "布鲁斯·施奈尔" },
    { ko: "필 짐머먼", en: "Phil Zimmermann", ja: "フィル・ジマーマン", zh: "菲尔·齐默尔曼" },
    { ko: "휘트필드 디피", en: "Whitfield Diffie", ja: "ホイットフィールド・ディフィー", zh: "惠特菲尔德·迪菲" },
    { ko: "마틴 헬먼", en: "Martin Hellman", ja: "マーティン・ヘルマン", zh: "马丁·赫尔曼" },
    { ko: "케빈 미트닉", en: "Kevin Mitnick", ja: "ケヴィン・ミトニック", zh: "凯文·米特尼克" },
    { ko: "리누스 토르발스", en: "Linus Torvalds", ja: "リーナス・トーバルズ", zh: "林纳斯·托瓦兹" },
  ],
  "novel:planning": [
    { ko: "J.R.R. 톨킨", en: "J.R.R. Tolkien", ja: "J.R.R.トールキン", zh: "J.R.R.托尔金" },
    { ko: "어슐러 르 귄", en: "Ursula K. Le Guin", ja: "アーシュラ・K・ル＝グウィン", zh: "厄休拉·勒古恩" },
    { ko: "프랭크 허버트", en: "Frank Herbert", ja: "フランク・ハーバート", zh: "弗兰克·赫伯特" },
    { ko: "아이작 아시모프", en: "Isaac Asimov", ja: "アイザック・アシモフ", zh: "艾萨克·阿西莫夫" },
    { ko: "조지 R.R. 마틴", en: "George R.R. Martin", ja: "ジョージ・R・R・マーティン", zh: "乔治·R·R·马丁" },
    { ko: "H.P. 러브크래프트", en: "H.P. Lovecraft", ja: "H.P.ラヴクラフト", zh: "H.P.洛夫克拉夫特" },
  ],
  "novel:dev": [
    { ko: "윌리엄 셰익스피어", en: "William Shakespeare", ja: "ウィリアム・シェイクスピア", zh: "威廉·莎士比亚" },
    { ko: "레프 톨스토이", en: "Leo Tolstoy", ja: "レフ・トルストイ", zh: "列夫·托尔斯泰" },
    { ko: "찰스 디킨스", en: "Charles Dickens", ja: "チャールズ・ディケンズ", zh: "查尔斯·狄更斯" },
    { ko: "가브리엘 마르케스", en: "Gabriel Garcia Marquez", ja: "ガブリエル・マルケス", zh: "加布里埃尔·马尔克斯" },
    { ko: "표도르 도스토옙스키", en: "Fyodor Dostoevsky", ja: "フョードル・ドストエフスキー", zh: "费奥多尔·陀思妥耶夫斯基" },
    { ko: "무라카미 하루키", en: "Haruki Murakami", ja: "村上春樹", zh: "村上春树" },
  ],
  "novel:design": [
    { ko: "데즈카 오사무", en: "Osamu Tezuka", ja: "手塚治虫", zh: "手冢治虫" },
    { ko: "월트 디즈니", en: "Walt Disney", ja: "ウォルト・ディズニー", zh: "沃尔特·迪士尼" },
    { ko: "미야자키 하야오", en: "Hayao Miyazaki", ja: "宮崎駿", zh: "宫崎骏" },
    { ko: "스탠 리", en: "Stan Lee", ja: "スタン・リー", zh: "斯坦·李" },
    { ko: "토리야마 아키라", en: "Akira Toriyama", ja: "鳥山明", zh: "鸟山明" },
    { ko: "뫼비우스", en: "Moebius", ja: "メビウス", zh: "莫比斯" },
  ],
  "novel:qa": [
    { ko: "버지니아 울프", en: "Virginia Woolf", ja: "ヴァージニア・ウルフ", zh: "弗吉尼亚·伍尔夫" },
    { ko: "해럴드 블룸", en: "Harold Bloom", ja: "ハロルド・ブルーム", zh: "哈罗德·布鲁姆" },
    { ko: "수전 손택", en: "Susan Sontag", ja: "スーザン・ソンタグ", zh: "苏珊·桑塔格" },
    { ko: "T.S. 엘리엇", en: "T.S. Eliot", ja: "T.S.エリオット", zh: "T.S.艾略特" },
    { ko: "새뮤얼 존슨", en: "Samuel Johnson", ja: "サミュエル・ジョンソン", zh: "塞缪尔·约翰逊" },
    { ko: "에드먼드 윌슨", en: "Edmund Wilson", ja: "エドマンド・ウィルソン", zh: "埃德蒙·威尔逊" },
  ],
  "novel:operations": [
    { ko: "맥스웰 퍼킨스", en: "Maxwell Perkins", ja: "マックスウェル・パーキンズ", zh: "麦克斯韦·珀金斯" },
    { ko: "베넷 서프", en: "Bennett Cerf", ja: "ベネット・サーフ", zh: "贝内特·瑟夫" },
    { ko: "앨프레드 노프", en: "Alfred Knopf", ja: "アルフレッド・クノップフ", zh: "阿尔弗雷德·克诺夫" },
    { ko: "앨런 레인", en: "Allen Lane", ja: "アレン・レーン", zh: "艾伦·莱恩" },
    { ko: "바니 로셋", en: "Barney Rosset", ja: "バーニー・ロゼット", zh: "巴尼·罗塞特" },
    { ko: "제이슨 엡스타인", en: "Jason Epstein", ja: "ジェイソン・エプスタイン", zh: "杰森·爱泼斯坦" },
  ],
  "novel:devsecops": [
    { ko: "볼테르", en: "Voltaire", ja: "ヴォルテール", zh: "伏尔泰" },
    { ko: "조지 오웰", en: "George Orwell", ja: "ジョージ・オーウェル", zh: "乔治·奥威尔" },
    { ko: "레이 브래드버리", en: "Ray Bradbury", ja: "レイ・ブラッドベリ", zh: "雷·布拉德伯里" },
    { ko: "살만 루시디", en: "Salman Rushdie", ja: "サルマン・ラシュディ", zh: "萨尔曼·拉什迪" },
    { ko: "존 밀턴", en: "John Milton", ja: "ジョン・ミルトン", zh: "约翰·弥尔顿" },
    { ko: "솔제니친", en: "Aleksandr Solzhenitsyn", ja: "アレクサンドル・ソルジェニーツィン", zh: "亚历山大·索尔仁尼琴" },
  ],
  "video_preprod:planning": [
    { ko: "스티븐 스필버그", en: "Steven Spielberg", ja: "スティーヴン・スピルバーグ", zh: "史蒂文·斯皮尔伯格" },
    { ko: "캐슬린 케네디", en: "Kathleen Kennedy", ja: "キャスリーン・ケネディ", zh: "凯瑟琳·肯尼迪" },
    { ko: "케빈 파이기", en: "Kevin Feige", ja: "ケヴィン・ファイギ", zh: "凯文·费奇" },
    { ko: "봉준호", en: "Bong Joon-ho", ja: "ポン・ジュノ", zh: "奉俊昊" },
    { ko: "제리 브룩하이머", en: "Jerry Bruckheimer", ja: "ジェリー・ブラッカイマー", zh: "杰瑞·布鲁克海默" },
    { ko: "데이비드 핀처", en: "David Fincher", ja: "デヴィッド・フィンチャー", zh: "大卫·芬奇" },
  ],
  "video_preprod:dev": [
    { ko: "앨프레드 히치콕", en: "Alfred Hitchcock", ja: "アルフレッド・ヒッチコック", zh: "阿尔弗雷德·希区柯克" },
    { ko: "스탠리 큐브릭", en: "Stanley Kubrick", ja: "スタンリー・キューブリック", zh: "斯坦利·库布里克" },
    { ko: "구로사와 아키라", en: "Akira Kurosawa", ja: "黒澤明", zh: "黑泽明" },
    { ko: "크리스토퍼 놀란", en: "Christopher Nolan", ja: "クリストファー・ノーラン", zh: "克里斯托弗·诺兰" },
    { ko: "마틴 스코세이지", en: "Martin Scorsese", ja: "マーティン・スコセッシ", zh: "马丁·斯科塞斯" },
    { ko: "박찬욱", en: "Park Chan-wook", ja: "パク・チャヌク", zh: "朴赞郁" },
  ],
  "video_preprod:design": [
    { ko: "로저 디킨스", en: "Roger Deakins", ja: "ロジャー・ディーキンス", zh: "罗杰·迪金斯" },
    { ko: "에마뉘엘 루베즈키", en: "Emmanuel Lubezki", ja: "エマニュエル・ルベツキ", zh: "埃曼努尔·卢贝兹基" },
    { ko: "비토리오 스토라로", en: "Vittorio Storaro", ja: "ヴィットリオ・ストラーロ", zh: "维托里奥·斯托拉罗" },
    { ko: "야누스 카민스키", en: "Janusz Kaminski", ja: "ヤヌス・カミンスキー", zh: "雅努什·卡明斯基" },
    { ko: "월리 피스터", en: "Wally Pfister", ja: "ウォーリー・フィスター", zh: "沃利·菲斯特" },
    { ko: "호이테 반 호이테마", en: "Hoyte van Hoytema", ja: "ホイテ・ヴァン・ホイテマ", zh: "霍伊特·范·霍特马" },
  ],
  "video_preprod:qa": [
    { ko: "월터 머치", en: "Walter Murch", ja: "ウォルター・マーチ", zh: "沃尔特·默奇" },
    { ko: "셀마 스쿤메이커", en: "Thelma Schoonmaker", ja: "セルマ・スクーンメイカー", zh: "塞尔玛·斯库梅克" },
    { ko: "리 스미스", en: "Lee Smith", ja: "リー・スミス", zh: "李·史密斯" },
    { ko: "마이클 칸", en: "Michael Kahn", ja: "マイケル・カーン", zh: "迈克尔·卡恩" },
    { ko: "샐리 멩케", en: "Sally Menke", ja: "サリー・メンケ", zh: "萨莉·门克" },
    { ko: "앤 V. 코츠", en: "Anne V. Coates", ja: "アン・V・コーツ", zh: "安·V·科茨" },
  ],
  "video_preprod:operations": [
    { ko: "어빙 탈버그", en: "Irving Thalberg", ja: "アーヴィング・タルバーグ", zh: "欧文·塔尔伯格" },
    { ko: "데이비드 셀즈닉", en: "David O. Selznick", ja: "デヴィッド・セルズニック", zh: "大卫·塞尔兹尼克" },
    { ko: "셰리 랜싱", en: "Sherry Lansing", ja: "シェリー・ランシング", zh: "雪莉·兰辛" },
    { ko: "잭 워너", en: "Jack Warner", ja: "ジャック・ワーナー", zh: "杰克·华纳" },
    { ko: "루이스 B. 메이어", en: "Louis B. Mayer", ja: "ルイス・B・メイヤー", zh: "路易斯·B·梅耶" },
    { ko: "루 와서먼", en: "Lew Wasserman", ja: "ルー・ワッサーマン", zh: "卢·瓦瑟曼" },
  ],
  "video_preprod:devsecops": [
    { ko: "레이 해리하우젠", en: "Ray Harryhausen", ja: "レイ・ハリーハウゼン", zh: "雷·哈里豪森" },
    { ko: "더글러스 트럼불", en: "Douglas Trumbull", ja: "ダグラス・トランブル", zh: "道格拉斯·特朗布尔" },
    { ko: "존 딕스트라", en: "John Dykstra", ja: "ジョン・ダイクストラ", zh: "约翰·戴克斯特拉" },
    { ko: "데니스 뮤런", en: "Dennis Muren", ja: "デニス・ミューレン", zh: "丹尼斯·缪伦" },
    { ko: "스탠 윈스턴", en: "Stan Winston", ja: "スタン・ウィンストン", zh: "斯坦·温斯顿" },
    { ko: "필 티펫", en: "Phil Tippett", ja: "フィル・ティペット", zh: "菲尔·蒂贝特" },
  ],
  "roleplay:planning": [
    { ko: "게리 가이객스", en: "Gary Gygax", ja: "ゲイリー・ガイギャックス", zh: "加里·吉盖克斯" },
    { ko: "미야모토 시게루", en: "Shigeru Miyamoto", ja: "宮本茂", zh: "宫本茂" },
    { ko: "코지마 히데오", en: "Hideo Kojima", ja: "小島秀夫", zh: "小岛秀夫" },
    { ko: "사카구치 히로노부", en: "Hironobu Sakaguchi", ja: "坂口博信", zh: "坂口博信" },
    { ko: "토드 하워드", en: "Todd Howard", ja: "トッド・ハワード", zh: "托德·霍华德" },
    { ko: "윌 라이트", en: "Will Wright", ja: "ウィル・ライト", zh: "威尔·赖特" },
  ],
  "roleplay:dev": [
    { ko: "아론 소킨", en: "Aaron Sorkin", ja: "アーロン・ソーキン", zh: "阿伦·索金" },
    { ko: "쿠엔틴 타란티노", en: "Quentin Tarantino", ja: "クエンティン・タランティーノ", zh: "昆汀·塔伦蒂诺" },
    { ko: "노라 에프런", en: "Nora Ephron", ja: "ノーラ・エフロン", zh: "诺拉·艾芙隆" },
    { ko: "찰리 카우프만", en: "Charlie Kaufman", ja: "チャーリー・カウフマン", zh: "查理·考夫曼" },
    { ko: "패디 차예프스키", en: "Paddy Chayefsky", ja: "パディ・チャイエフスキー", zh: "帕迪·查耶夫斯基" },
    { ko: "데이비드 매밋", en: "David Mamet", ja: "デヴィッド・マメット", zh: "大卫·马梅特" },
  ],
  "roleplay:design": [
    { ko: "이시오카 에이코", en: "Eiko Ishioka", ja: "石岡瑛子", zh: "石冈瑛子" },
    { ko: "콜린 앳우드", en: "Colleen Atwood", ja: "コリーン・アトウッド", zh: "柯琳·阿特伍德" },
    { ko: "H.R. 기거", en: "H.R. Giger", ja: "H.R.ギーガー", zh: "H.R.吉格尔" },
    { ko: "시드 미드", en: "Syd Mead", ja: "シド・ミード", zh: "席德·米德" },
    { ko: "릭 베이커", en: "Rick Baker", ja: "リック・ベイカー", zh: "里克·贝克" },
    { ko: "줄리 테이머", en: "Julie Taymor", ja: "ジュリー・テイモア", zh: "朱莉·泰莫" },
  ],
  "roleplay:qa": [
    { ko: "조셉 캠벨", en: "Joseph Campbell", ja: "ジョセフ・キャンベル", zh: "约瑟夫·坎贝尔" },
    { ko: "칼 융", en: "Carl Jung", ja: "カール・ユング", zh: "卡尔·荣格" },
    { ko: "블라디미르 프롭", en: "Vladimir Propp", ja: "ウラジーミル・プロップ", zh: "弗拉基米尔·普罗普" },
    { ko: "크리스토퍼 보글러", en: "Christopher Vogler", ja: "クリストファー・ヴォグラー", zh: "克里斯托弗·沃格勒" },
    { ko: "로버트 맥키", en: "Robert McKee", ja: "ロバート・マッキー", zh: "罗伯特·麦基" },
    { ko: "블레이크 스나이더", en: "Blake Snyder", ja: "ブレイク・スナイダー", zh: "布莱克·斯奈德" },
  ],
  "roleplay:operations": [
    { ko: "게이브 뉴얼", en: "Gabe Newell", ja: "ゲイブ・ニューウェル", zh: "加布·纽维尔" },
    { ko: "이와타 사토루", en: "Satoru Iwata", ja: "岩田聡", zh: "岩田聪" },
    { ko: "필 스펜서", en: "Phil Spencer", ja: "フィル・スペンサー", zh: "菲尔·斯宾塞" },
    { ko: "레지 피서메", en: "Reggie Fils-Aime", ja: "レジー・フィサメ", zh: "雷吉·菲尔斯-埃梅" },
    { ko: "시드 마이어", en: "Sid Meier", ja: "シド・マイヤー", zh: "席德·梅尔" },
    { ko: "리처드 게리엇", en: "Richard Garriott", ja: "リチャード・ギャリオット", zh: "理查德·盖瑞特" },
  ],
  "roleplay:devsecops": [
    { ko: "존 카맥", en: "John Carmack", ja: "ジョン・カーマック", zh: "约翰·卡马克" },
    { ko: "팀 스위니", en: "Tim Sweeney", ja: "ティム・スウィーニー", zh: "蒂姆·斯威尼" },
    { ko: "켄 레빈", en: "Ken Levine", ja: "ケン・レヴィン", zh: "肯·莱文" },
    { ko: "마르쿠스 페르손", en: "Markus Persson", ja: "マルクス・ペルソン", zh: "马库斯·佩尔松" },
    { ko: "이와이 토시오", en: "Toshio Iwai", ja: "岩井俊雄", zh: "岩井俊雄" },
    { ko: "제시 셸", en: "Jesse Schell", ja: "ジェシー・シェル", zh: "杰西·谢尔" },
  ],
};
